### ISSUE TITLE
Treeview not found

### ISSUE THREAD

**Issue by Oreolek** [kartik-v/yii2-tree-manager#107]
When trying to do a migration with nestedSetBehaviour:

`Exception: Trying to get property of non-object (/var/www/katundo/source/vendor/kartik-v/yii2-tree-manager/models/Tree.php:350)`

The problem seems to be with the line getting `$module->treeStructure`, where `$module = TreeView::module()`

**Comment by kartik-v** [comment]
You need to read documentation for setup and usage of the module and [setup the module](http://demos.krajee.com/tree-manager#setup-module) as described in the docs.
