### ISSUE TITLE
Problem with deleting node

### ISSUE THREAD

**Issue by andynador** [kartik-v/yii2-tree-manager#108]
I try to remove node, and got error 

> SQLSTATE[42803]: Grouping error: 7 ОШИБКА: колонка "auth_item.lft" must appear in GROUP BY expression
>  LINE 1: ..."lft" > $1) AND ("rgt" < $2)) AND ("root"=$3) ORDER BY "lft" ^ The SQL being executed was: SELECT COUNT(*) FROM "tree" WHERE (("lft" > 1) AND ("rgt" < 2)) AND ("root"=8) ORDER BY "lft"

I use PostgreSQL. Problem in file **TreeTrait**, line 372, while calling 

> $this->children()->count()

**softDelete** in config I set to _false_. 

.

**Comment by truth4oll** [comment]
The same error on postgres
