### ISSUE TITLE
Pass parameters to view from _form.php

### ISSUE THREAD

**Issue by davidsoutoc** [kartik-v/yii2-tree-manager#109]
Hi, 
I want use the information about tree on my view. If I change this line I can use this information:
vendor/kartik-v/yii2-tree-manager/views/_form.php
[Line 114]]    //return $this->render($nodeAddlViews[$part], $p);
                     return $this->render($nodeAddlViews[$part], array('params' => $p));

With this, I can use the information with the variable "$params".
Do you have solution for this or maybe I have to create a branch and pull request with this option?
Thanks for your help.

**Comment by kartik-v** [comment]
Why do you need to do that?

You can directly access the parameters like `node`, `form`, `action` etc. in your node additional views. You do not need a `params` array to store that and retrieve it.
