### ISSUE TITLE
I try to implement this extension but for empty data is throw error

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-tree-manager#11]
I read in @creocoder must initial a default root to database ?

First running application give
```php
PHP Warning – yii\base\ErrorException
Creating default object from empty value
```
If must insert initial data, what the default data or query to insert root node ?

**Comment by kartik-v** [comment]
If you check the [tree manager demo](http://demos.krajee.com/tree-manager-demo/tree-view) - the tree view widget includes a **create root** button in the toolbar. When you first launch this widget on an empty database table you can use this button to create a new root. You can use this subsequently to create more roots if you need.

See related discussion #2.

**Comment by adiramardiani** [comment]
I not see the create root button, only show this error, no rendered view
![download](https://cloud.githubusercontent.com/assets/8703419/6654763/4713b88e-cb0c-11e4-991d-89781648c85b.png)

**Comment by kartik-v** [comment]
The widget does not create any data on init.

Ensure you have [read the documentation](http://demos.krajee.com/tree-manager#getting-started) and configured the module attributes correctly extending. Try to first replicate the demo database structure exactly and test. Especially see if you have set the `treeAttribute` and have it in your db table.

This is what you should see on an empty database table as shown below in the screenshot (real one for the demo case).

![initkrajeetree](https://cloud.githubusercontent.com/assets/3592619/6654783/be06d400-cb00-11e4-9625-40f958c73e09.png)
.

**Comment by adiramardiani** [comment]
I'm still confused by the mention of 'Product' and 'Tree' between [Documentation](http://demos.krajee.com/tree-manager) and [ReadMe Github](https://github.com/kartik-v/yii2-tree-manager)
And in [Schema Documentation](http://demos.krajee.com/tree-manager#prepare-database) is same with schema in schema\tree.sql ?
Is there an update query that most, or all the same

**Comment by kartik-v** [comment]
That's because you as a developer can name your db table OR model class anything. The only requirements are:

- your model AR class must extend from `kartik\tree\models\Tree` 
- your table name method in the above AR class must reflect your db table 

that's all, whether you use `Product` or `Tree` or `Category`... it does not matter. In fact as a developer, one may need multiple tree tables or models based on their own scenarios - they may be used across the app in any name... its just configurable.
