### ISSUE TITLE
I can understand attributes 'root' and 'depth',but how to calculate 'lft' and 'rgt'? thx

### ISSUE THREAD

**Issue by chenbuer** [kartik-v/yii2-tree-manager#115]
the 'lft' and 'rgt' could change sometimes if I add new node

**Comment by bubifengyun** [comment]
这是另外一篇论文里提到的。现在只是使用，没有细究怎么回事。这篇论文可以在这个代码的readme里找到线索。由于我是手机上网，不方便给你查找，你可以自己搜搜看。非常抱歉，你发了几个邮件，我不知道你是不是收到了，还是在黑名单里。有问题可以在这里开issue，也可以在我的那篇博客里写下来，谷歌邮件貌似用着不是那么顺手 https://github.com/bubifengyun/book-yii2-dev-process

**Comment by bubifengyun** [comment]
https://github.com/creocoder/yii2-nested-sets/blob/master/README.md

貌似这个nested sets，你可以百度一下他是怎么回事的。

**Comment by chenbuer** [comment]
@bubifengyun 谢啦，感谢您能回复。我刚刚查看了一下邮箱，没看见。以后还是用126（chenzy08@126.com）。
这个问题就不纠结了，现在在搞treemanager右边的编辑表单，我看你修改的是nodeView，但是demo里面修改的是nodeAddlViews，在_form.php中修改似乎并不奏效。
看_form.php中，渲染的还是nodeAddlViews视图：
`$renderContent = function ($part) use ($nodeAddlViews, $params, $form) {
    if (empty($nodeAddlViews[$part])) {
        return '';
    }
    $p = $params;
    $p['form'] = $form;
    return $this->render($nodeAddlViews[$part], $p);
};`

**Comment by bubifengyun** [comment]
抱歉，现在只能手机上网，有时间我把代码分享一下吧，我感觉那篇博客说的够详细的了，可能还有没有提到的地方，如果你有啥问题，可以在我那边说，发邮件貌似不容易沟通。

**Comment by kartik-v** [comment]
You can refer [yii2-nested-sets extension docs](https://github.com/creocoder/yii2-nested-sets) for the same.
