### ISSUE TITLE
Version not upgraded

### ISSUE THREAD

**Issue by pctin** [kartik-v/yii2-tree-manager#116]
I added to my composer.json: "kartik-v/yii2-tree-manager": "@dev"
Minimun stability: "minimum-stability": "stable"
Installed but not found class TreeTrait in models folder then I checked the version in kartik\tree\models\Tree is 1.0.2

Is it error or How can I upgrade to 1.0.6 for using TreeTrait via Composer?

**Comment by pctin** [comment]
I posted this 2 days ago but no support until now! Does my problem cause from my stupid?

**Comment by kartik-v** [comment]
This is more to do with using composer. You may want to read composer documentation.

Check your app's composer json for right package dependencies (or if you are having conflicts that push only version). If you are not clear you may want to remove all packages from composer and only install yii2-tree-manager and see if it installs the right version and then slowly add the other packages.
