### ISSUE TITLE
Migrations error

### ISSUE THREAD

**Issue by greg-repo** [kartik-v/yii2-tree-manager#125]
Class 'm230416_200116_tree' not found in /Users/Usersname/Sites/Sitename/vendor/yiisoft/yii2/console/controllers/MigrateController.php on line 170

**Comment by HanafiAhmat** [comment]
Hi @kartik-v,

I am facing the same issue as mentioned by @greg-repo above.
After removing the namespace declaration in `m230416_200116_tree.php` file, migration works fine.

`// namespace kartik\tree\migrations;`

I installed this extension on basic app using yii version 2.0.8.
If the namespace declaration is not intended to be there, I can create a pull request.

**Comment by kartik-v** [comment]
OK pls submit a PR
