### ISSUE TITLE
How to separate textual "name" field for translation purpose?

### ISSUE THREAD

**Issue by kwazaro** [kartik-v/yii2-tree-manager#126]
I have multilingual project and some realization with two database tables for each structure (pages, products, categories). For example, the tree database table "category" should have non-textual data (id, icon, created_at etc), and the table "category_content" should have the translatable textual data, like "name", "description", "meta_title" etc with field "language_code". Tables connected with relation, based on current application language (Yii::$app->language). like this:
```php
public function getCategoryContent()
{
    return $this->hasOne(CategoryContent::className(), ['category_id' => 'id'])->andWhere(['category_content.language_code' => Yii::$app->language]);
}
```
But how can I use Tree module with such structure, if "name" attribute is strictly configured by module in "category" table? It's better to separate such text-based field, because I have different names for nodes in different languages. When I create a node, I want to save two "names" - for two languages (one new node element to mysql "category" table and connected two new elements to "category_content" table for two different languages). Extending the default controller, model and view for module seems to me very hard, because of ajax, javascript and so on - very difficult module logic for "hooking" (it's not just adding additional form fields to view "_form" file). Is there a better solution to make Tree realy multilingual including its contents?

**Comment by kartik-v** [comment]
You can always control your Tree model irrespective of your database structure. For example you could have a `translated_name` attribute in your module (or a getter) that is auto calculated and can be set in the `nameAttribute` settings for the Tree model.
