### ISSUE TITLE
Wrong view. Error

### ISSUE THREAD

**Issue by samsandr** [kartik-v/yii2-tree-manager#131]
Hi @kartik-v, 
I installed Yii 2 Tree Manager extension to my project via composer, but it does not work as needed.
I created migration and applied it. Then I created model and then added module to my configure file config/web.php. Then I created action in my SiteController that renders view and created new view with TreeView Widget. I attach two screens with my problems: all elements n view are not in right place, almost all buttons are disabled and all of them does nt work, also I got a mitake -  585 Uncaught ReferenceError: treeview_63999a19 is not defined, it is on second screenshot. Why it happends, why it does not work as expected?
![default](https://cloud.githubusercontent.com/assets/5465020/17083945/44770f98-51b8-11e6-8ebe-bcd79df1ad91.png)
![2](https://cloud.githubusercontent.com/assets/5465020/17083944/44764982-51b8-11e6-8032-5aad5bb9f12d.png)

![default](https://cloud.githubusercontent.com/assets/5465020/17083947/7ba94d28-51b8-11e6-9058-9d8f001157a0.png)
![2](https://cloud.githubusercontent.com/assets/5465020/17083948/7bacd5ba-51b8-11e6-8ee4-036d5ac5d162.png)

**Comment by xiaohei2015** [comment]
@samsandr I also encountered this issue, so could you please help to share your solution if you resolved this? Thx a lot.

**Comment by kartik-v** [comment]
You need to first check your code and see if there are no javascript errors or third party jquery plugin conflicts with on your page. By default the widget loads the treeview plugin settings in a randomly javascript variable in the HEAD part of the output view. You must ensure you have the HEAD section in your document... and / or modify the `jsLoadPosition` if not.
