### ISSUE TITLE
SluggableBehavior

### ISSUE THREAD

**Issue by mydesign** [kartik-v/yii2-tree-manager#134]
If extend model Tree default config SluggableBehavior take error
`exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: common\models\Tree::parents()'`

How to use other widgets and behaviors to Tree model?

```
<?php

namespace common\models;

use Yii;
use yii\behaviors\SluggableBehavior;

class Tree extends \kartik\tree\models\Tree
{
    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'name',
                //'slugAttribute' => 'slug',
                //'immutable' => true,
            ],
        ];
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tree';
    }

    public function rules()
    {
          $rules = parent::rules();
          $rules[] = ['text', 'safe'];
          $rules[] = ['slug', 'unique'];
          return $rules;
    }   
}

?>
```

**Comment by kartik-v** [comment]
Merge your behavior with `parent::behaviors()`.

**Comment by vadimua757** [comment]
This code will help you
`public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors [] =
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'name',
                'immutable' => true
            ];
        return $behaviors;
    }`
