### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by LarryTX** [kartik-v/yii2-tree-manager#14]
Is there any chance that you could post a working example of how this module is used. I've tried following your step-by-step instructions, but they're just not working for me. For instance, in Getting Started, I went through steps 1, 2, and 3 with no problem. Then in Step 4, Using TreeView widget, it says "In your view files, you can now use the tree view directly to manage tree data as shown below. ..." Now, I have to say: What view files? What controller? What actions? Do I assume that the model will use the NodeController? Do I create a controller and have it extend NodeController?

Then your instructions say to refer to the treeview section for details. Now, it plunges right in to telling me how to set up the widget. Set is up where? I still don't have a controller or view to set it up in.

The only view that I find in the extension is a _form.php partial. I don't know if I'm supposed to understand what that is doing or if I'm supposed to be using it.

I know that it is hard to write technical documentation for this stuff. (I spent over eight years of my life very successfully writing similar technical documentation.) You clearly have make a heroic effort to write documentation, and perhaps I am just stupid. Nonetheless, your documentation just isn't working for me. If I could see all the relevant files from a functioning usage, I could probably reverse engineer it.

**Comment by kartik-v** [comment]
### NOTE
You may want to post these help related questions mainly on the [TreeView Demo](http://demos.krajee.com/tree-manager-demo/tree-view) and [TreeViewInput Demo](http://demos.krajee.com/tree-manager-demo/tree-view-input) pages so other developers can help answer. Use this project page primarily for logging issues.

### On Working Example:
There is already an elaborate demo example provided for [TreeView Demo](http://demos.krajee.com/tree-manager-demo/tree-view) and [TreeViewInput Demo](http://demos.krajee.com/tree-manager-demo/tree-view-input).

I am not sure what is the difficulty for you in understanding. Note the following assumptions which may not be documented
- core yii functionalities and jargons. The developer must have a knowledge of yii before using the extensions. So for example when the doc mentions **view files** they are a part of the MVC view component in yii.
- the documentation tries to highlight extension specific usage only. No help is necessarily provided on how you design your yii application... that is left to the developer.

Coming back to your query
> Now, it plunges right in to telling me how to set up the widget. Set is up where? I still don't have a controller or view to set it up in.
There is no rocket science here. How would you use any widget or input in your application (e.g. a Select2, Checkbox). You would need to design this as part of your Yii MVC application wherever you want to display the TreeView.

**Comment by LarryTX** [comment]
Thank you so much for your condescension. I am very much aware of how to use the Yii2 and have used the MVC pattern in Yii 1., Yii2,m Laravel, CakePHP, Drupal, and several others that I forget at the moment. As to TreeView Input, I do understand that that is a widget to be used much like in any other widget in views associated with a model.

 

My questions clearly centered on the TreeView widget. With that, again, you are singularly unhelpful and condescending.

 

Larry E. Lutz

**Comment by kartik-v** [comment]
Great. If you are already aware of Yii MVC concepts - then I need to know what else is missing for enhancing the documentation - so that I could look through it.

- I feel it should be straightforward for a yii developer to render/echo the TreeView widget like any other Yii widget in your view. If you are not clear on this let know.
- Since you mention you are able to understand TreeViewInput widget - it should be similar for TreeView with slightly different params (since the TreeViewInput widget extends the TreeView).
- If you need to know the parameters that the TreeView widget needs - then it is documented in [TreeView widget settings](http://demos.krajee.com/tree-manager#tree-view)
- If you need to figure out as a demo what the important parameters to the TreeView are - then you can [set some of the important settings in the demo here](http://demos.krajee.com/tree-manager-demo/tree-view#tree-view-config) and check the dynamic code needed. You can also test the impact of the settings in the demo.

As I said, I need to know what is it you are not able to follow for documenting for the benefit of others..

**Comment by LarryTX** [comment]
The part that is totally missing is where to render the TreeView widget. (I obviously understand MVC. If you note, my question centered on how to implement the controller and views for my TreeView-related model. After all, one has to have a controller and views.)

 

After much stumbling around, I figured out that I need to have a controller for my model, let’s say a model named Product with a controller named ProductController. What I was trying to figure out was what to put into that controller. So, again, totally stumbling around with no guidance whatsoever, I added an index action to the controller. (From your code, it looked like the extension might expect a “manage” action, but what the heck.)

 

So then, I rendered the TreeView widget in index.php. Now, I am able to create and save entries into the table.

 

All of that may sound very simple to you, but it’s not. First, most extensions that provide model, controller, and view(s) expect that you use the ones provided by the extension and not create your own. (Try dektrium/User for example.) So, I go wading through all the morass of information in the highly detailed documentation on how to set up TreeView trying to figure it all out when a simple set of instructions would have gotten me there without all the stumbling around, guessing what to do next, getting frustrated because the supposedly step-by-step instructions go A, B, C, F, G, M,N, with nothing at all about E, D, H, and so on. Gaps in otherwise good documentation completely throw the user off.

 

By the way, you suggest overriding asDisabled in setting up the model. Yes, I know that, if you read and digest every single line in your documentation, you should know that having it return true will render the whole widget fundamentally disabled. However, you have to fully digest everything before you fully realize what you’re doing. At the point where the user is trying to wade through everything and make sense of it all, you through a completely off-the-wall example that basically renders the widget disabled. Why confuse the user with something so trivial and irrelevant at that point. You know that he wants to be able to create entries; leave him with a functional, not disabled widget. Put side issue embellishments later.

 

Well, now, I’m able to create categories and display a beautiful dropdown with the entries in it. Unfortunately, it isn’t saving my selection to the table. And I want to be able to display the result in a hierarchy like “Item » Subitem » SubsubItem”. I won’t ask you for any assistance with that. After all, you understand every new thing and concept instantaneously with no confusion, no stumbling around, no time needed to let it all sink in and form a coherent entity. I’ll try to find someone who understands mere mortals.

 

Larry E. Lutz

**Comment by kartik-v** [comment]
In case you need some help on the code or building use cases with the extension - please point it out in the site comments section for other developers to help on your use case. Closing this.

**Comment by mtangoo** [comment]
I think I'm facing same issue though this conversation helped me clear some fogs. I think main issue is the relation between Widgets and module. You mentioned it works transparently, but that is not clear in documentation.

Thanks
