### ISSUE TITLE
Update to 1.0.6 breaks application

### ISSUE THREAD

**Issue by schmunk42** [kartik-v/yii2-tree-manager#148]
We are using tree-manager under the hood of https://github.com/dmstr/yii2-pages-module

## Steps to reproduce the issue

1. Go to /pages
2. Try to load a page

## Expected behavior and actual behavior

When I follow those steps, I see an error message:

```
array_values() expects parameter 1 to be array, string given
```

![bildschirmfoto 2016-12-21 um 19 48 52](https://cloud.githubusercontent.com/assets/649031/21402006/d75f2e02-c7b6-11e6-9040-a3f691571aa7.png)

I was expecting to see the edit form.

#### Browsers

- [X] Google Chrome

#### Operating System

- [X] Linux Docker

#### Libraries

- yii2-tree-manager version: 1.0.6

**Comment by def1oyd** [comment]
I've also noticed this problem.
https://github.com/kartik-v/yii2-tree-manager/blob/master/controllers/NodeController.php#L126
$iconsList doesn't guarantee to be an array.
I disabled the checkSignature() and it worked

**Comment by yanhuixie** [comment]
Hi, kartik, also found in _form.php ? I'm not sure about it, have just upgraded it to @dev today.
![qq 20161224200051](https://cloud.githubusercontent.com/assets/1049615/21466904/bd0b1b38-ca13-11e6-80e4-21e607ee1419.png)
