### ISSUE TITLE
"array_values() expects parameter 1 to be array, string given" @dev

### ISSUE THREAD

**Issue by yanhuixie** [kartik-v/yii2-tree-manager#149]
Hi, kartik, we have found a issue in _form.php, not sure about it now, have just upgraded it to @dev today. ("kartik-v/yii2-tree-manager": "@dev")
With the TreeView::widget settings as follow, as we disable icons in this page.
```php
    ...
    'iconEditSettings'  => [
        'show' => 'none',
        'type' => TreeView::ICON_CSS,
        'listData' => []
    ]
```
> array_values() expects parameter 1 to be array, string given

![qq 20161224200051](https://cloud.githubusercontent.com/assets/1049615/21466904/bd0b1b38-ca13-11e6-80e4-21e607ee1419.png)

I try to fix it, replace 
```php
$dataToHash = $modelClass . !!$isAdmin . !!$softDelete. !!$showFormButtons . !!$showIDAttribute .
    $currUrl . $nodeView . $nodeSelected . Json::encode($formOptions) .
    Json::encode($nodeAddlViews) . Json::encode(array_values($iconsList)) . 
    Json::encode($breadcrumbs);
```
to
```php
$dataToHash = $modelClass . !!$isAdmin . !!$softDelete. !!$showFormButtons . !!$showIDAttribute .
    $currUrl . $nodeView . $nodeSelected . Json::encode($formOptions) .
    Json::encode($nodeAddlViews) . 
	(is_array($iconsList) ? Json::encode(array_values($iconsList)) : $iconsList) . 
	Json::encode($breadcrumbs);
```

**Comment by kartik-v** [comment]
Duplicate to #148 and fixed there.

**Comment by yanhuixie** [comment]
Hi @kartik-v 
I did see the #148 before, kartik~ and I have just moved my reply of #148 to here as a topic issue. We already using the @dev version, and the error occures, too. I noticed that you had fixed NodeController.php two days ago, but I think this issue is related to _form.php.

**Comment by kartik-v** [comment]
You may want to update to the latest from `dev-master`. There are a few recent commits that you may not be having.

**Comment by yanhuixie** [comment]
wow~ I get it now. Thank you, kartik!
