### ISSUE TITLE
Is it possible to add id value to each item in tree?

### ISSUE THREAD

**Issue by niksan8989** [kartik-v/yii2-tree-manager#152]
I want each item in the tree would have id value after his name. For example, It have to look like "Page Name (2)" where "(2)" is node id. How can I do that?

**Comment by kartik-v** [comment]
Yes... you need to set the `TreeView::nodeLabel` property as an array or Closure. This will be documented.

**Comment by niksan8989** [comment]
Thank you so much!

**Comment by niksan8989** [comment]
Sorry, but I didn`t find TreeView::nodeLabel property. I also didn`t find that in documentation. Could you please give me more detail information?

**Comment by kartik-v** [comment]
[Here](https://github.com/kartik-v/yii2-tree-manager/blob/master/TreeView.php#L112)

**Comment by kartik-v** [comment]
Refer about [nodeLabel in the docs as well](http://demos.krajee.com/tree-manager#treeview-nodeLabel).

**Comment by niksan8989** [comment]
Got it. Thank you.
