### ISSUE TITLE
My code can run at 1.0.5 but failed at 1.0.6

### ISSUE THREAD

**Issue by ScottHuangZL** [kartik-v/yii2-tree-manager#153]
I just upgrade tree manager from 1.0.5 to 1.0.6 at Dec 27.
My code show array_value error.  So I have to copy the backuped 1.0.5 back to overwrite 1.0.6, and then ok again. 

My code do not change anything.  So, do 1.0.6 have any broken change need pay attention?

**Btw, my code contain below additionalView. it is new version do not handle nodeAddlViews correctly? Thanks.**

'nodeAddlViews' => [
            kartik\tree\Module::VIEW_PART_1 => '@app/views/eop/approval-tree/additionalView',
        ],

**Comment by maz0717** [comment]
Duplicate to #148 and fixed there.

**Comment by kartik-v** [comment]
Yes upgrade to latest v1.0.7 from dev-master... this will be tagged soon.
