### ISSUE TITLE
Syntax error on NodeController.php line 137

### ISSUE THREAD

**Issue by maz0717** [kartik-v/yii2-tree-manager#154]
I just now updated to the latest version and get the following error when trying to view a node with the widget.

<pre>Exception &#039;ParseError&#039; with message &#039;syntax error, unexpected quoted-string (T_CONSTANT_ENCAPSED_STRING)&#039; 

in C:\Users\maz07\projects\gsys\vendor\kartik-v\yii2-tree-manager\controllers\NodeController.php:137

Stack trace:
#0 C:\Users\maz07\projects\gsys\vendor\composer\ClassLoader.php(301): Composer\Autoload\includeFile(&#039;C:\\Users\\maz07\\...&#039;)
#1 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(&#039;kartik\\tree\\con...&#039;)
#2 [internal function]: spl_autoload_call(&#039;kartik\\tree\\con...&#039;)
#3 C:\Users\maz07\projects\gsys\vendor\yiisoft\yii2\base\Module.php(564): class_exists(&#039;kartik\\tree\\con...&#039;)
#4 C:\Users\maz07\projects\gsys\vendor\yiisoft\yii2\base\Module.php(522): yii\base\Module-&gt;createControllerByID(&#039;node&#039;)
#5 C:\Users\maz07\projects\gsys\vendor\yiisoft\yii2\base\Module.php(514): yii\base\Module-&gt;createController(&#039;manage&#039;)
#6 C:\Users\maz07\projects\gsys\vendor\yiisoft\yii2\base\Module.php(448): yii\base\Module-&gt;createController(&#039;node/manage&#039;)
#7 C:\Users\maz07\projects\gsys\vendor\yiisoft\yii2\web\Application.php(100): yii\base\Module-&gt;runAction(&#039;treemanager/nod...&#039;, Array)
#8 C:\Users\maz07\projects\gsys\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application-&gt;handleRequest(Object(yii\web\Request))
#9 C:\Users\maz07\projects\gsys\backend\web\index.php(18): yii\base\Application-&gt;run()
#10 {main}</pre>

**Comment by maz0717** [comment]
I removed the quotes on that line and it seems to work fine.  Also actually does resolve issue #150.

**Comment by maz0717** [comment]
One recommendation.  My previous patch checked for the existence of session for the same purpose.  Checking session would be a little more flexible because it would allow the widget to work without a session setup.  Just no security.  It would also be nice if the new security feature was configurable.

**Comment by kartik-v** [comment]
Yes - the session handling check can exist without testing the need for console apps.

On your next query, the module uses JavaScript based data handling and transfer of data for POST submissions... hence it will not be possible to implement this security for console apps (where you will not have a browser front end to parse javascript).

**Comment by kartik-v** [comment]
Yes - the session handling check can exist without testing the need for console apps.

On your next query, the module uses JavaScript based data handling and transfer of data for POST submissions... hence it will not be possible to implement this security for console apps (where you will not have a browser front end to parse javascript).

EDIT: 
If you need to use the security feature without sessions... then just set a value for `Module::treeEncryptSalt` yourself in the module settings... no sessions will be needed. This will be documented.
