### ISSUE TITLE
The navigation icon missing when I update to latest tree-manager today

### ISSUE THREAD

**Issue by ScottHuangZL** [kartik-v/yii2-tree-manager#169]
I just use composer to update my widgets
And find tree manager navigation icon missing after upgrade, it .
For example: 
When I hover mouse on that placeholder it still pop up hint to show that button as below 
"Add New", "Add New Root", "Delete", "Move Up","Move Down"
but missing icon.

Can you help to on it? Thanks.

**Comment by kartik-v** [comment]
You need to check if iconic fonts are getting loaded on your page and if you have done something that is breaking or not loading the icons. e.g. If `fontAwesome` property is set to `true` font awesome assets and CSS must be loaded.

**Comment by ScottHuangZL** [comment]
The  fontAwesome property is set to true.
I just set it as false, and the icon show up again.
