### ISSUE TITLE
can not load model when add new root

### ISSUE THREAD

**Issue by tentruycapcuaban** [kartik-v/yii2-tree-manager#171]
hi kartik, can you show me how to fix it???
```
{"name":"Exception","message":"This operation is not allowed.","code":0,"type":"yii\\base\\InvalidCallException","file":"D:\\wamp64\\www\\thsams\\vendor\\kartik-v\\yii2-tree-manager\\controllers\\NodeController.php","line":128,"stack-trace":["#0 D:\\wamp64\\www\\thsams\\vendor\\kartik-v\\yii2-tree-manager\\controllers\\NodeController.php(286): kartik\\tree\\controllers\\NodeController::checkValidRequest()","#1 [internal function]: kartik\\tree\\controllers\\NodeController->actionManage()","#2 D:\\wamp64\\www\\thsams\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(55): call_user_func_array(Array, Array)","#3 D:\\wamp64\\www\\thsams\\vendor\\yiisoft\\yii2\\base\\Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)","#4 D:\\wamp64\\www\\thsams\\vendor\\yiisoft\\yii2\\base\\Module.php(455): yii\\base\\Controller->runAction('manage', Array)","#5 D:\\wamp64\\www\\thsams\\vendor\\yiisoft\\yii2\\web\\Application.php(84): yii\\base\\Module->runAction('treemanager/nod...', Array)","#6 D:\\wamp64\\www\\thsams\\vendor\\yiisoft\\yii2\\base\\Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#7 D:\\wamp64\\www\\thsams\\web\\index.php(12): yii\\base\\Application->run()","#8 {main}"]}
```
![image](https://user-images.githubusercontent.com/17898925/29599271-cfb2d9f8-87f8-11e7-8d47-5309a01954df.png)

**Comment by tentruycapcuaban** [comment]
look seem can not load _form

**Comment by Spillo89** [comment]
I have the same issue, do you have fixed in some ways?

**Comment by Erkebulan69** [comment]
Faced the same issue, seems that Trait implementation is not working (as Tree extend method works well)

**Comment by kartik-v** [comment]
With the trait implementation you need to define all the other public properties in your model as mentioned in the [documentation for setting up your model](http://demos.krajee.com/tree-manager#setup-model). You can also cross check the default model class `kartik\tree\models\Tree` to check which properties you must define.

**Comment by kartik-v** [comment]
On the model not loading - just debug your code to show the error messages of the model.

Note that the TreeView widget on load expects a `displayValue` which is important to show the default node model when initializing the tree view.

**Comment by lowap** [comment]
Hi Kartik, and what if there are no error messages. I have a working model, I have duplicated it (in DB as well in yii2), and the new one just keeps loading.
