### ISSUE TITLE
Read Only and Disabled method Not affecting on new fields of form

### ISSUE THREAD

**Issue by bahrammzm** [kartik-v/yii2-tree-manager#173]
i have added some new fields to my form . but some of methods like read only and disabled not affecting on these new fields  and generally how can i determine which fields should be have disabled attribute or not in my extended method ?

**Comment by kartik-v** [comment]
I have no idea how you are generating new fields in your form and what are those. The `readonly` and `disabled` methods in `kartik\form\ActiveForm` is applicable only for native HTML inputs and input widgets designed by Krajee starting with `kartik` namespace.
