### ISSUE TITLE
problem with views/_form

### ISSUE THREAD

**Issue by Spillo89** [kartik-v/yii2-tree-manager#176]
Hi to all, i've just installed kartik to manage my tree, i followed the documentation and configured the first TreeView widget.
 Now i create in the database my root folder called Aziendale but when i try to click on the + button, the form in the right just disappear, and if i click on my folder nothing happend. i have to refresh.
My view page:

```
<?php
use kartik\tree\TreeView;
use common\models\db\BACN2NBachecaNode2Node;


echo TreeView::widget([
    // single query fetch to render the tree
    // use the Product model you have in the previous step
    'query' => BACN2NBachecaNode2Node::find()->addOrderBy('root, lft'),
    'headingOptions' => ['label' => 'Documenti bacheca'],
    'rootOptions' => ['label'=>'<span class="text-primary">Bacheca</span>'],
    'fontAwesome' => true,     // optional
    'isAdmin' => false,         // optional (toggle to enable admin mode)
    'displayValue' => 1,        // initial display value
    'softDelete' => true,
    'cacheSettings' => [
        'enableCache' => false   // defaults to true
    ]
]);
?>
```

![screenshot_4](https://user-images.githubusercontent.com/7600542/32222900-5fbf2a6a-be3b-11e7-8815-8b1133fe111e.png)
![screenshot_3](https://user-images.githubusercontent.com/7600542/32222901-5fe67070-be3b-11e7-86bd-77ec490bb891.png)

I really don't get what i'm missing, can someone help me? Thanks

**Comment by liugehao** [comment]
<![CDATA[YII-BLOCK-HEAD]]><![CDATA[YII-BLOCK-BODY-BEGIN]]>{"out":"The view file does not exist: /var/www/html/dyna2/vendor/kartik-v/yii2-tree-manager/views/node/_form.php","status":"error"}

move file views/_form.php to views/node/_form.php

**Comment by kartik-v** [comment]
Read [the comment in the related PR](https://github.com/kartik-v/yii2-tree-manager/pull/182#issuecomment-355752696). This does not seem to be correct.. note that you need to check that the `kartik\tree\Module::nodeView`  defaults to `@kvtree/views/_form` and it should render this form correctly by default.... you need  ensure you have the yii2-tree-manager module configured correctly in your configuration file as described in docs.
