### ISSUE TITLE
Invalid request signature detected during tree data manage action

### ISSUE THREAD

**Issue by EndErr** [kartik-v/yii2-tree-manager#187]
## Prerequisites

- [*] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [*] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [*] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [*] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [*] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. I use app-practical-a, the extension worked fine and after update some month ago I started to get the error "Invalid request signature detected during tree data manage action! Please refresh the page and retry." and details with OLD HASH and NEW HASH when clicking on a item in the tree.
2. Did cleaning all the assets, cache, deinstall and reinstall also.

## Expected behavior and actual behavior

When I follow those steps, I see... the error above.

I was expecting... a working edit of the item.

#### Browsers

- [*] Google Chrome
- [*] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [*] Windows as client machine
- [ ] Mac OS X
- [*] Linux as hosting machine
- [ ] Mobile

#### Libraries

- jQuery version: 
- yii2-tree-manager version: latest

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [*] The bug happens consistently across all tested browsers
- [*] This bug happens when using yii2-tree-manager without other plugins.

**Comment by kartik-v** [comment]
Check the OLD HASH and NEW HASH data - some data is changing before and after you submit the form for save... for example check if you are using date time or some setting to set the filename or other - avoid such things that can tamper the data and change it.
