### ISSUE TITLE
jQuery.treeview is not a function 

### ISSUE THREAD

**Issue by buttflattery** [kartik-v/yii2-tree-manager#193]
i am having problems on the live site I am getting 

> jQuery.treeview() is not a function 

on the live site i just installed composer and pulled the latest code on the local version i have no problems loading the page or treeview manager but on the live site it is displaying the above error the reason i narrowed down looks to be the recent updated as running `composer show -i` on live and local project shows 2 different versions 

On Live version is `kartik-v/yii2-tree-manager          dev-master 048282a`
On Local envioronment version is `kartik-v/yii2-tree-manager          dev-master 3021504` 

When I override the local file for the treeview manager it started working correctly can you please check what could be the problem in the latest update which is raising the exception.

Although the cource file for the treeview script is loaded i have verified and the error is on the line where it call the treeview ie
`jQuery('#w0').treeview(treeview_7216c1db);`

**Comment by kartik-v** [comment]
Related to #192 and solved via the last commit. Get the updated code.

**Comment by buttflattery** [comment]
umm, i ran composer with `composer install` the same time when i added the issue should i run `composer update` now @kartik-v

**Comment by buttflattery** [comment]
just saw the thread seems like i added the issue in the same time lapse as when you fixed it `2 Hours` ago will update if it is not fixed
