### ISSUE TITLE
TreeViewInput after PJAX

### ISSUE THREAD

**Issue by mryndin** [kartik-v/yii2-tree-manager#194]
Hi !
I`m using TreeViewInput with modal dialog & PJAX loading data.

In https://github.com/kartik-v/yii2-widget-switchinput/issues/23

You told about pjaxContainerId property.

I can use this property in this case ?

If I can, please, show example.

**Comment by kartik-v** [comment]
You need to match this id to the container to which you set in the Yii `Pjax` widget.
