### ISSUE TITLE
controller in included views not correct

### ISSUE THREAD

**Issue by lowap** [kartik-v/yii2-tree-manager#195]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

I have added this to TreeView:

`'nodeAddlViews' => [
    Module::VIEW_PART_2 => '@app/views/pmgrp/view'
]`
it's a standard view generated with **giiant**. Now in this view I have Gridviews for related data. 

## Expected behavior and actual behavior

Everything is working fine, the only problem is, that if I want to click on the eye to open the detailview of a certain record in the gridview, it's not working because the path is false:

http://app/ **treemanager** /controller/action

I was expecting...

http://app/controller/action...

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-tree-manager version: 9999999-dev

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-tree-manager without other plugins.

**Comment by kartik-v** [comment]
It is obvious - because you are using the module's controller action to render your view... you need to edit your GridView Action Column button settings to set the right controller action URL

**Comment by lowap** [comment]
Hi, I've tried to edit Action Column button settings, but unfortunately I can't figure it out how to do it in order to make controller `treemanager` go away. Can you please point me to the right direction? Please? Thank you in advance!

**Comment by kartik-v** [comment]
Read the yii2 documentation to understand how to use the GridView and grid columns - for your use case ... check the [urlCreator property](https://www.yiiframework.com/doc/api/2.0/yii-grid-actioncolumn#$urlCreator-detail) of GridView ActionColumn.

**Comment by lowap** [comment]
So I have Treemanager (the house), and on the top of it, I have a view (the roof). And you say, there is the opportunity to change the controller of the house, from the roof? As I see, it doesn't matter what I'm doing with the urlCreator, the `treemanager` will be always the same. I can only change what is coming after it...?

**Comment by kartik-v** [comment]
It depends on how you have coded your app. This is actually more on how you program and setup your GridView (and actually nothing to do with this tree-manager module).

I do not have time to share code. You can always skip/hide rendering the default buttons of the GridView Action column and render your own Action Column ... for example setup [the template](https://www.yiiframework.com/doc/api/2.0/yii-grid-actioncolumn#$template-detail) property to some of your custom actions:

```php
// your ActionColumn settings
'template' =>'{custom-update}', // hide other buttons and build your own button
'buttons' => [
    'custom-update' => function ($url, $model, $key) {
        return Html::a('Update', ['/your-controller/your-action', 'id' => $model->id]) : '';
    },
]
```

Please read the yii2 documentation to understand or recommend to post Yii2 related programming queries in the yii2-forum.

**Comment by lowap** [comment]
I don't believe that: I was trying something very similar, and it was not working. Now it's working. Crazy. Thank you very much!

**Comment by lowap** [comment]
There is still a bug somewhere: when I load the page, and haven't yet clicked on any node, I see the correct url without `treemanager`. But as soon as I'm clicking on any node, there is `treemanager` again in the url, but only in the third related tab. I have 3 different relations, also 3 different tabs and gridviews to 3 different tables, and however the code regarding actioncolumn/url for detailview is totally the same, the urls/links in the first two tabs are correct, in the third not... it drives me nuts but it's like this.
