### ISSUE TITLE
How to properly init db

### ISSUE THREAD

**Issue by Konrad90** [kartik-v/yii2-tree-manager#2]
Hi Kartik
When I try to use TreeView widget with an empty db table I get "PHP Fatal Error: Call to a member function parents() on null" in yii2-tree-manager/views/_form.php line 24.
How do I properly initialize the table?

**Comment by kartik-v** [comment]
You need to build this validation in your controller action that renders the tree manager - for example;

```php
$records; // track count in db table
if ($records > 0) {
   Yii::$app->session->setFlash('error', 'Huh! No records in tree');
   $this->redirect('/site/errorpage');
}
$this->render(/site/treepage');
```

**Comment by kartik-v** [comment]
You need to build this validation in your controller action that renders the tree manager - for example;

```php
$records; // track count in db table
if ($records == 0) {
   Yii::$app->session->setFlash('error', 'Huh! No records in tree');
   $this->redirect('/site/errorpage');
}
$this->render(/site/treepage');
```

**Comment by kartik-v** [comment]
You need to build this validation in your controller action that renders the tree manager - for example;

```php
$records; // track count in db table
if ($records == 0) {
   Yii::$app->session->setFlash('error', 'Huh! No records in tree');
   return $this->redirect('/site/errorpage');
}
return $this->render(/site/treepage');
```

**Comment by kartik-v** [comment]
You need to build this validation in your controller action that renders the tree manager - for example;

```php
$records; // track count in db table
if ($records == 0) {
   Yii::$app->session->setFlash('error', 'Huh! No records in tree');
   return $this->redirect('/site/errorpage');
}
return $this->render('/site/treepage');
```

**Comment by kartik-v** [comment]
You need to build this validation in your controller action that renders the tree manager - for example;

```php
if (!$tableExists) { // db table does not exist
   Yii::$app->session->setFlash('error', 'Huh! No database available');
   return $this->redirect('/site/errorpage');
}
return $this->render('/site/treepage');
```

**Comment by Konrad90** [comment]
Thanks. I did it like that to create the first entries: 
```php
if (Tree::find()->count() == 0) {
            $home = new Tree(['name' => 'Home']);
            $home->makeRoot();
            $site1 = new Tree(['name' => 'Site 1']);
            $site1->prependTo($home);
        }
```
TreeView widget works now. I can add normal nodes but when I try to create a new root node I get another error "Undefined variable: parent" in yii2-tree-manager/controllers/NodeController.php line 105.

**Comment by kartik-v** [comment]
Note you must have a database table created for the extension that should be reflected in your model.

You do not need to initialize tree via controller. You can if you want... but the widget can do it for you. Check the create root button icon in the toolbar to create a new root and proceed from there.

**Comment by Konrad90** [comment]
Ok. I used the tree.sql file from the schema folder and the minimal Model from the readme. It looks like this: 
```php
  namespace dmstr\modules\pages\models;

    use Yii;

    class Tree extends \kartik\tree\models\Tree
    {
        /**
        * @inheritdoc
        */
        public static function tableName()
        {
            return 'tbl_tree';
        }
    }
```
It's not initializing the tree for me though.

**Comment by kartik-v** [comment]
Ok upgrade to the latest version from dev-master. You can initialize tree via widget and also create a new root.

The extension has two new properties `emptyNodeMsg` and `emptyNodeMsgOptions` to help configure the message shown on init.

**Comment by kartik-v** [comment]
Ok upgrade to the latest version from dev-master. You can initialize tree via the widget itself and also create a new root.

The extension has two new properties `emptyNodeMsg` and `emptyNodeMsgOptions` to help configure the message shown on init.

**Comment by Konrad90** [comment]
Thanks. When creating a root node I now get the error "Undefined variable: parent" in yii2-tree-manager/controllers/NodeController.php at line 105. But when I reload the page the node is there, so it works. I guess $parentKey == 'root' is not getting set.

**Comment by kartik-v** [comment]
You probably did not have the updated code - since I did not push the tested code up.

Do check and update now.

**Comment by Konrad90** [comment]
thanks. there are no php errors anymore
