### ISSUE TITLE
Enhance data hashing and security via a separate helper

### ISSUE THREAD

**Issue by buttflattery** [kartik-v/yii2-tree-manager#205]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [x] This is not a usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [x] This is not a general programming/coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Install extension
2.customize the view
3.Update the extension to the latest release

## Expected behavior and actual behavior
On an update to the latest release, the new `$dataToHash` which consist of the several items including the 
new attributes that were recently added like `nodeTitle` and `nodeTitlePlural`  should be adjusted accordingly 

### Actual Behaviour ###
It throws exception as the signatures dont match and i have to manually copy the new attributes and place them at the exact place they are added in the extensions `yii2-tree-manager/views/_form.php` file.

> Invalid request signature detected during tree data manage action! Please refresh the page and retry.
> 
> OLD HASH:
> 94461115ae4caa395ace47710903879d4ed8665964bb586a226907cefb94d39acommon\models\Campaign111/manage-campaigns@backend/views/campaign/_formnodenodes{"id":"w0-nodeform"}{"1":"","2":"","3":"","4":"","5":""}{"submit":"","reset":" "}"none"{"activeCss":"active","depth":"","glue":" » ","untitled":"Untitled"}
> NEW HASH:
> 3657c070219bec63de1ae8fa39fd1ed212d64816db4d6a4675314f8cd7b31470common\models\Campaign111/manage-campaigns@backend/views/campaign/_formw0-nodeselnodenodes{"id":"w0-nodeform"}{"1":"","2":"","3":"","4":"","5":""}{"submit":"","reset":" "}"none"{"activeCss":"active","depth":"","glue":" » ","untitled":"Untitled"}

Is there a possibility that we convert this form into a widget rather than a view so that the defaults like `$dataToHash` are automatically adjusted on update if there are additions to it? or maybe anyother way to fix this problem.

## Environment
Yii 2.0.15.1
Ubuntu 14.04
Php 7.2

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari 

#### Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-tree-manager version: dev-master 8ab3047

## Isolating the problem

- [x] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-tree-manager without other plugins.

**Comment by kartik-v** [comment]
This will be enhanced in the upcoming release.
