### ISSUE TITLE
Enhancements to support Bootstrap 4.x

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-tree-manager#206]
- New `bsVersion` property included in `Module`, `TreeView` and `TreeViewInput` 
- Bootstrap 4.x will use Font Awesome Free 5.x icons by default - and will not be impacted by the `fontAwesome` setting.
- New icon properties added in `TreeView` and `TreeViewInput` to default Bootstrap icons better:
  - `defaultChildNodeIcon`
  - `defaultParentNodeIcon`
  - `defaultParentNodeOpenIcon`
  - `defaultExpandNodeIcon`
  - `defaultCollapseNodeIcon`
  - `defaultCheckedNodeIcon`
  - `defaultCheckedNodeIcon`

**Comment by dimonikus** [comment]
Calling unknown method: kartik\tree\TreeView::initBsVersion()

**Comment by antonshell** [comment]
> Calling unknown method: kartik\tree\TreeView::initBsVersion()

Updating yii2-krajee-base to v1.9.9 solved problem for me.

```
composer update kartik-v/yii2-krajee-base "dev-master"
```

**Comment by kartik-v** [comment]
Latest release of yii2-krajee-base is v2.0 ... check your composer version dependencies to ensure you have latest releases of the extensions.
