### ISSUE TITLE
Toolbar buttons disabled

### ISSUE THREAD

**Issue by LarryTX** [kartik-v/yii2-tree-manager#208]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [x ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Installed "kartik-v/yii2-tree-manager": "dev-master"
2. Followed instructions at http://demos.krajee.com/tree-manager meticulously, copying and pasting wherever possible.
3. Displayed index.php in Chrome and Firefox browsers.

## Expected behavior and actual behavior
Be able to add records using the toolbar buttons.

When I follow those steps, I see...
The left panel with toolbar buttons at the bottom. All toolbar buttons are grayed (disabled). When I click them, nothing happens. The mouse cursor does not change to a hand when I hover over them.
I was expecting...
To be able to add a record by clicking the plus button.

In researching on Google, I found one posting wherein the person said that it would work if you added an initial record manually with: root=1, rgt=1, lft=1, lvl=0, name=SomeName. When I did that, I got this error message: Calling unknown method: backend\modules\associations\models\AssociationCategories::parents()
#### Browsers

- [X ] Google Chrome - version 68
- [X ] Mozilla Firefox - version 62
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ X] Windows - 10 Pro
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.2.1
- yii2-tree-manager version: dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [ x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-tree-manager without other plugins.

**Comment by LarryTX** [comment]
Actually, with regard to Option 1, I must not have been clear when I said, "All toolbar buttons are grayed (disabled)." All, in this case, includes the tree icon. Clicking on it does nothing. I did go back in, and added 'allowNewRoots'  => true, to the widget even though your instructions make no mention of it. I cleared the browser history, refreshed the page, and the tree icon still does nothing.

**Comment by kartik-v** [comment]
>  and added 'allowNewRoots' => true, to the widget even though your instructions make no mention of it

Refer widget properties - [allowNewRoots](http://demos.krajee.com/tree-manager#treeview-allowNewRoots) ... will need to understand your issue clearly - as I mentioned you need to find the way to populate records in your db tables... the db inserts/updates are controlled mainly by creocoder/yii2-nested-sets extension

**Comment by kartik-v** [comment]
I suppose updating to version 1.1.0 would resolve blank tree root creation problems. Check and let know.
