### ISSUE TITLE
How to hide iconslist form?

### ISSUE THREAD

**Issue by scmember** [kartik-v/yii2-tree-manager#212]
Hello!

Need to hide iconslist. The best I could is to add a line to _form from component, before line 249 

`<?php $iconsList = 'none'; ?>`

it works but it's a very dirty hack. How can I set iconslist to none from module config or something?

thanks

**Comment by kartik-v** [comment]
Set it in `iconEditSettings` of `TreeView` widget:

```php
use kartik\tree\TreeView;
echo TreeView::widget([
    'iconEditSettings' => ['show' => 'none'],  // to hide the icons list
   // other settings
]);
```

**Comment by scmember** [comment]
Unfortunatly it didn't work because of value is array, not string...

![image](https://user-images.githubusercontent.com/5699583/45931810-cc0bad00-bf7b-11e8-9a29-a0782e615559.png)


![image](https://user-images.githubusercontent.com/5699583/45931791-95ce2d80-bf7b-11e8-884f-3c804e4e7df9.png)

**Comment by kartik-v** [comment]
Not sure what the problem is from your end... here is what is passed to `$iconsList` in the view [via the method `getIconsList`](https://github.com/kartik-v/yii2-tree-manager/blob/master/src/TreeView.php#L1503)

**Comment by scmember** [comment]
Well, just debugged it, here is the results:

1) here we see that a proper value has passed to $__nodeIconsList
![image](https://user-images.githubusercontent.com/5699583/45973512-5f5de480-c047-11e8-885e-30f7087b942d.png)
2) then we see that a proper value has passed to iconsList attribute
![image](https://user-images.githubusercontent.com/5699583/45973735-f32fb080-c047-11e8-8f16-f5763e1b522c.png)
3) But! right after that we see that a proper string value magically becomes an array!
![image](https://user-images.githubusercontent.com/5699583/45973895-5f121900-c048-11e8-95fd-d113826f0ccc.png)
4) So this condition will never be satisfied because of wrong type of iconsList
![image](https://user-images.githubusercontent.com/5699583/45973995-badca200-c048-11e8-9de3-00eb724d7733.png)

Seems like a problem is in parseManageData method:
![image](https://user-images.githubusercontent.com/5699583/45974095-07c07880-c049-11e8-99ac-170bed49ff23.png)

**Comment by kartik-v** [comment]
Provided a fix. Check & confirm if resolved.

**Comment by scmember** [comment]
now it works like a charm! Thanks for quick support!
