### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by cleverus** [kartik-v/yii2-tree-manager#213]
![image](https://user-images.githubusercontent.com/42825616/46097449-a32d2700-c1ca-11e8-8aba-d5dfa28fd4bd.png)

**Comment by Sonit90** [comment]
Add comma after 'Дочерние элементы разрешены', or use @dev version:

> php composer.phar require kartik-v/yii2-tree-manager "@dev"

**Comment by cleverus** [comment]
> Add comma after 'Дочерние элементы разрешены', or use @dev version:
> 
> > php composer.phar require kartik-v/yii2-tree-manager "@dev"

I know how fix it, so I'm just reporting an error
