### ISSUE TITLE
TreeView::getDefaultIconPrefix()

### ISSUE THREAD

**Issue by cresusjpt** [kartik-v/yii2-tree-manager#214]
i'm trying to use the tree manager, i getting this error while rendering the view : <b>Calling unknown method: kartik\tree\TreeView::getDefaultIconPrefix()</b> Can someone help?

**Comment by kartik-v** [comment]
You have an incorrect installation with outdated dependencies. Update packages via composer to get all updated dependencies. You seem to have just updated yii2-krajee-base manually without having the dependency yii2-krajee-base updated.

**Comment by cresusjpt** [comment]
thanks
