### ISSUE TITLE
Get node without children

### ISSUE THREAD

**Issue by gledsoneduardo** [kartik-v/yii2-tree-manager#218]
How get a list of node without children, using the example:
id: 4 => iPhone 6
id: 5 => iPhone 5s
id: 6 => iPhone 4
id: 8 => iPad Air
.....
(sorry my terrible english)

**Comment by kartik-v** [comment]
You need to go through `creocoder/yii2-nested-sets` extension docs and/or post such queries/issues in that repo.

The method to use for your use case should be the `isLeaf` method as [described in the code here](https://github.com/creocoder/yii2-nested-sets/blob/master/src/NestedSetsBehavior.php#L322)
