### ISSUE TITLE
Input Format for Kartik-v/yii2-tree-manager

### ISSUE THREAD

**Issue by dazzlers1** [kartik-v/yii2-tree-manager#224]
Hi,
 I am using 'kartik-v yii2-tree-manager'.  In this I have to follow the same table structure as mentioned in the documentation. But I have different permissions for each sub-child. I have to combine 2 tables to display the tree node values. Is it possible to pass the data as an array so that I can write a new action to fetch data from both the tables. If it is possible let me know the array format. Now I am stuck with this. Please help.

**Comment by kartik-v** [comment]
`yii2-tree-manager` depends/relies on 'creocoder/yii2-nested-sets' extension for tree behavior management which uses a NestedSetsBehavior on a single model (typically mapped to a single table).

So you need to design your application accordingly. However the `yii2-tree-manager` provides a few abilities to dynamically control various such permission scenarios by allowing you to override the table level defaults at the `Tree` model level - by allowing you to override the methods like `isActive`, `isMovable` etc. within the model which can be used to get user id level accesses or data from other tables. Check the docs.

**Comment by dazzlers1** [comment]
When submitting the tree form, it posts the checked ids. I think the ids are primary key from the table. Is there any option to set different id for child items?
 ie; Main item id : 1 (Master)
Sub item id : 1_2 (Facility - Now the id is 2.. can I attach main item id with sub item???)
