### ISSUE TITLE
TinyMCE issue

### ISSUE THREAD

**Issue by ajoudeh** [kartik-v/yii2-tree-manager#225]
Dear,

I tried to use TinyMCE with TreeManagerView but on the second select, TinyMCE not working. only woking on the first select

![q1 10-15-2018 5-25-50 pm](https://user-images.githubusercontent.com/1451200/46957045-6359b100-d09f-11e8-835d-f5993d0b4132.png)

Thanks,

**Comment by kkkko** [comment]
Same problem

**Comment by kkkko** [comment]
Try this https://github.com/kartik-v/yii2-tree-manager/issues/191
In my case plugin's events doesn't work, so i solved a problem by this:
$('#w0-tree ul li').on('click', function(event, key, jqXHR, settings) {
    tinymce.remove();
});
Where $('#w0-tree ul li') - selector of tree item
