### ISSUE TITLE
possible bug in css for icons in directory structure

### ISSUE THREAD

**Issue by attybean** [kartik-v/yii2-tree-manager#227]
## Steps to reproduce the issue

1. composer require version  1.1.1 (upgrading from version 1.08)

## Expected behavior and actual behavior

When I follow those steps, I see...

Icons 'open folder, closed folder, parent folder' in the 'directory structure' are showing at the same time. (three icons back to back in front of the file name in the tree)

I was expecting...

only one icon in front of the folder/file and the others hidden

#### Browsers
- [ x] Google Chrome

#### Operating System
- [x ] Windows
Win 7 64bit PRO English

#### Libraries
- php 7.0.31
- yii2 2.0.16
- jQuery version: v3.2.1
- yii2-tree-manager version: 1.1.1

## Isolating the problem
 The old kv-tree.css file had this line: (204)
```
.kv-tree-container .kv-node-closed, .kv-tree-container .kv-node-opened, .kv-tree-container .kv-icon-parent, .kv-node-toggle, .kv-parent >
 .kv-tree-list >
  .kv-node-detail >
   .kv-node-icon.kv-icon-child {
    display: none;
}
```
The new one does not. So I added it back to my own css file and everything works as expected.

**Comment by kartik-v** [comment]
The CSS in the updated version already exists in the form of tree wrapper:
```php
.kv-tree-wrapper .kv-node-closed, .kv-tree-wrapper .kv-node-opened, .kv-tree-wrapper .kv-icon-parent,
.kv-node-toggle, .kv-parent > .kv-tree-list > .kv-node-detail > .kv-node-icon.kv-icon-child {
    display: none;
}
```
Check if you have the latest release of the extension and are running the latest CSS on the browser (ensure browser is not loading from a stale cache and clean cache and restart).
Have you overridden the TreeView classes or changed any of the code yourself?

**Comment by attybean** [comment]
TreeView was extended and the initOptions was missing a few lines. Now it works perfectly without any modifications. Thank you so much for your dedication and hard work. @kartik-v
