### ISSUE TITLE
nodeViewParams are not passed to nodeAddlViews and to ajax loaded form also if custom view

### ISSUE THREAD

**Issue by sviluppo** [kartik-v/yii2-tree-manager#228]
## Expected behavior and actual behavior

If you set **nodeViewParams** the params are passed to the custom view.
But not on the view loaded with ajax (/node/manage) and on the custom part set with **nodeAddlViews**.
I have an additional CustomId in the Model that i need to set without user manipulation.
I have used a workaround in the partial of **nodeAddlViews** using an explode of $currUrl, but is ugly.

I was expecting...
that this param was reachable.

#### Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.2.1
- yii2-tree-manager version: 1.1.1

**Comment by kartik-v** [comment]
Recording a potential enhancement.
