### ISSUE TITLE
How to show different Item for each nodes of tree?

### ISSUE THREAD

**Issue by rahmanjalayer** [kartik-v/yii2-tree-manager#231]
I have a tree that has some nodes in hierarchically manner. I want to show some textBox when is clicked on root items but when is clicked on level 1 nodes, I want to display another Items and etc.
as default is displayed same Items (id,name,icon,iconType) for all nodes.
thanks in advance.

**Comment by rahmanjalayer** [comment]
Please help me to solve this problem. :(

**Comment by kartik-v** [comment]
Read docs about customizing/configuring/overriding your own node detail view by reading about [nodeView](http://demos.krajee.com/tree-manager#treeview-nodeView) and [nodeAddlViews](http://demos.krajee.com/tree-manager#treeview-nodeAddlViews)
