### ISSUE TITLE
No Migration found

### ISSUE THREAD

**Issue by kavasey** [kartik-v/yii2-tree-manager#232]
Hello,
Thank you for your good and marvellous yii2 widgets.

**yii migrate/up --migrationPath=@vendor/kartik-v/yii2-tree-manager/migrations**

_No new migrations found. Your system is up-to-date._

Had to change it to 
**yii migrate/up --migrationPath=@vendor/kartik-v/yii2-tree-manager/src/migrations**
Perhaps the docs or README needs to be updated?

Additional errors
Apply the above migrations? (yes|no) [no]:yes
*** applying m180628_055357_alter_tree
    > add column child_allowed boolean NOT NULL DEFAULT TRUE to table {{%tree}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'doobia_dev.tree' doesn't exist

Again it is applying the alter_tree migration before the tree migration hence the errors.

Am I missing something?
Thanks

**Comment by kartik-v** [comment]
Thanks. The migration path has been corrected in documentation.
