### ISSUE TITLE
array instead of query?

### ISSUE THREAD

**Issue by rahmanjalayer** [kartik-v/yii2-tree-manager#235]
there is a code in widget like follow:
'query'             => Tree::find()->addOrderBy('root, lft'), 
but I want to give an array instead of query. like bellow:
'query'             =>dataArray;
 How can I do it?

**Comment by kartik-v** [comment]
It has to be a `yii\db\query` object and is database query based dependent on yii2-nested-sets extension. It requires a database table to be setup as mentioned in docs.
