### ISSUE TITLE
How to add a new parameter in tree view widget?

### ISSUE THREAD

**Issue by rahmanjalayer** [kartik-v/yii2-tree-manager#237]
I'm using tree view in my project. I want to set a new param in treeView widget like follow:
```
 echo \kartik\tree\TreeView::widget([
        'query' => \backend\models\Regulation::find()->addOrderBy('root, lft')->andWhere(['selectedForParvandeh' => $parvandehVersionID])->andWhere(['>', 'lvl', '0']),
        'rootOptions' => ['label' => '<span class="text-primary">p1</span>'],
        'topRootAsHeading' => true, // this will override the headingOptions
        'fontAwesome' => true,
        'isAdmin' => true,
        'iconEditSettings' => [
            'show' => 'none',
        ],
        'softDelete' => false,
        'cacheSettings' => ['enableCache' => true],
        'calledFrom' => true,
    ]);
```
as you can see above, "calledFrom" param is added. I want to access to this in nodeController. for this reason, I've added follow code in TreeView class:
`public $calledFrom = false;`
then I edited at renderDetail function:
```
$manageData = TreeSecurity::parseManageData([
            'formOptions' => $this->nodeFormOptions,
            'modelClass' => $modelClass,
            'formAction' => $this->nodeActions[Module::NODE_SAVE],
            'currUrl' => $url,
            'isAdmin' => $this->isAdmin,
            'gg' => $this->gg,
            'iconsList' => $this->_nodeIconsList,
            'softDelete' => $this->softDelete,
            'allowNewRoots' => $this->allowNewRoots,
            'showFormButtons' => $this->showFormButtons,
            'showIDAttribute' => $this->showIDAttribute,
            'showNameAttribute' => $this->showNameAttribute,
            'nodeView' => $this->nodeView,
            'nodeAddlViews' => $this->nodeAddlViews,
            'nodeViewButtonLabels' => $this->nodeViewButtonLabels,
            'nodeSelected' => $this->_nodeSelected,
            'breadcrumbs' => $this->breadcrumbs,
            'noNodesMessage' => Html::tag('div', $this->emptyNodeMsg, $this->emptyNodeMsgOptions),
            'nodeTitle' => $this->nodeTitle,
            'nodeTitlePlural' => $this->nodeTitlePlural,
            'defaultBtnCss' => $this->getDefaultBtnCss(),
            'calledFrom' => $this->calledFrom,

        ]);
```
to make long story short, I've added "calledFrom" variable every where which "isAdmin" is used.
but I can't access it within nodeController/actionManage.
I know my description is complicated. but I would be thankful, if you could help me to define a new param and use it in nodeController/actionManage.

**Comment by rahmanjalayer** [comment]
there is no one can help me??!!!!! :(

**Comment by kartik-v** [comment]
You can just add additional custom attributes to your TreeModel [as described here](http://demos.krajee.com/tree-manager#model-custom-attributes) with appropriate validation rules.

Then you can just include these additional attributes as inputs in your tree node form that will be automatically parsed by the NodeController.

To add additional inputs just set them your custom view and configure in [nodeAdditionalViews](http://demos.krajee.com/tree-manager#treeview-nodeAddlViews)

**Comment by fasi1208** [comment]
I don't want to add the additional parameters as inputs in my tree. I want to make work them in background.
