### ISSUE TITLE
Correct CSS class hide for Bootstrap 4.x

### ISSUE THREAD

**Issue by myname1614** [kartik-v/yii2-tree-manager#239]
there is not enough some css files to hide blocks

![image](https://user-images.githubusercontent.com/34938365/53696456-cb4f3080-3dcf-11e9-9ed2-bf65f322ae83.png)

**Comment by myname1614** [comment]
after composer update, clean assets, cache, cookie I see this:

![image](https://user-images.githubusercontent.com/34938365/53726636-11ab9a80-3e77-11e9-87ab-61c51ea744bd.png)

**Comment by kartik-v** [comment]
This seems a stale JS caching issue at your end. You seem to have an outdated JS rendered on your client browser and NOT sending the `hideCssClass` property with the hash. Update to latest assets from the repo and retry (cross check what version of JS is running on your client versus the version of the JS on the repo dev-master).

**Comment by myname1614** [comment]
thanks, my mistake. I did clear frontend assets, instead backend.
