### ISSUE TITLE
Can we set 'dataStructure' configuration in Widget instead of in web\config\Module?

### ISSUE THREAD

**Issue by ScottHuangZL** [kartik-v/yii2-tree-manager#24]
As title.
In case I want to add new fields for specific Tree but not for all Trees.
```
echo TreeView::widget([
// single query fetch to render the tree
// use the Product model you have in the previous step
        'query' => ApprovalTree::find()->addOrderBy('root, lft'),
        'headingOptions' => ['label' => 'Approval_Tree'],
        'fontAwesome' => true, // optional
        'isAdmin' => false, // optional (toggle to enable admin mode)
        //'displayValue' => 11, // initial display value
        'softDelete' => true, // defaults to true
        'cacheSettings' => [
            'enableCache' => true // defaults to true
        ],
        'showCheckbox' => false,
        'multiple' => false,
        'nodeAddlViews' => [
            kartik\tree\Module::VIEW_PART_1 => '@app/views/eop/approvaltree/additionalView',
        ],
// such as enable below setting.
//        'dataStructure' => [
//            'keyAttribute' => 'id',
//            'nameAttribute' => 'name',
//            'user_idAttribute' => 'user_id',
//            'iconAttribute' => 'icon',
//            'iconTypeAttribute' => 'icon_type'
//        ],
]
);
```
Thanks.

**Comment by kartik-v** [comment]
Not possible currently - because the dataStructure has to be fixed and is used across various sessions including javascript validations and whenever the record is saved via controller and redirects. These cannot be passed in a straightforward manner if set from widget.

You need to have a common model structure for attributes ... but you can choose to display attributes which you NEED for specific forms... by extending the model and creating variants.

**Comment by ScottHuangZL** [comment]
I think it is possible, since you still can set key/name/icon/iconType as default. Just allow widget to add more new attribute like below, and merge it with module default setting.

// such as enable below setting.
        'addDataStructure' => [
            'user_idAttribute' => 'user_id',  //this is additional field which add by end user, actually, end user can add more field.
        ],

**Comment by kartik-v** [comment]
I may need time to check this as it may not be straightforward. Feel free to submit a PR though. Reopening this.

**Comment by kartik-v** [comment]
Refer enhancement #25.

You can now set `TreeView::showIDAttribute` to show / hide the ID attribute.
