### ISSUE TITLE
The 'treemanager' module MUST be setup in your Yii configuration file.

### ISSUE THREAD

**Issue by masaini** [kartik-v/yii2-tree-manager#242]
After complete installation i have get this type error. 
any guys suggestions me.
![screenshot_2019-03-04 invalid configuration yii base invalidconfigexception](https://user-images.githubusercontent.com/46594872/53735710-b5b03880-3ead-11e9-830e-8ecf797b4f57.png)

**Comment by kartik-v** [comment]
Read the documentation before you start using the extension OR before you log issues. You need to follow the [documentation here for getting started to use this extension](http://demos.krajee.com/tree-manager#getting-started).

The error above is self explanatory - you have not set the module as described in docs [in this place](http://demos.krajee.com/tree-manager#setup-module)
