### ISSUE TITLE
alert on add and delete node

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-tree-manager#243]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
followed demo
![screenshot 23](https://user-images.githubusercontent.com/8582472/53874679-e9fc3400-4028-11e9-90bb-8c51917b237b.png)

I was expecting...
no alert
#### Browsers
all browser
- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-tree-manager version:
latest
## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-tree-manager without other plugins.

**Comment by kartik-v** [comment]
Duplicate to #239 and resolved via that. Check if you have updated extension and cleaned up stale assets and cache.
