### ISSUE TITLE
Unknown Input Appearing on the bottom

### ISSUE THREAD

**Issue by buttflattery** [kartik-v/yii2-tree-manager#244]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

There is a strange input at the bottom that is appearing in the treeview 

![image](https://user-images.githubusercontent.com/1536454/54231558-8db67a00-452a-11e9-8854-d90b8c608a90.png)

Looking into the inspector it shows the input as 

`<input type="text" id="w0" class="form-control hidden-xs" name="kv-node-selected" value="" data-key="1" data-krajee-treeview="treeview_60a25e70">`

## Steps to reproduce the issue

1. If I am using the default options provided on the demo page even then it shows the same with the default view. 

Below is the code provided

```
<?php

    use common\models\Campaign;
    use kartik\tree\Module;
    use kartik\tree\TreeView;
    use yii\helpers\Html;
    use yii\helpers\Url;

    /* @var $this yii\web\View */
    /* @var $searchModel common\models\CampaignSearch */
    /* @var $dataProvider yii\data\ActiveDataProvider */

    $this->title = 'Campaigns';
    $this->params['breadcrumbs'][] = $this->title;
 

    /*detect if user is allowed to create update the campaing */
    $appId = Yii::$app->id;
    $route = $appId . "/node/save";
?>

<div class="campaign-create">
    <div class="card">
        <div class="header">
            <h2>
                <?php echo Html::encode($this->title) ?>
                <small>Manage Campaigns</small>
            </h2>



        </div>
        <div class="body">

            <?php echo
                TreeView::widget([
                    // single query fetch to render the tree
                    // use the Campaign model you have in the previous step
                    'query' => Campaign::find()->addOrderBy('root, lft'),
                    'headingOptions' => ['label' => 'Store'],
                    'rootOptions' => ['label'=>'<span class="text-primary">Products</span>'],
                    'topRootAsHeading' => true, // this will override the headingOptions
                    'fontAwesome' => true,
                    'isAdmin' => true,
                    'iconEditSettings'=> [
                        'show' => 'list',
                        'listData' => [
                            'folder' => 'Folder',
                            'file' => 'File',
                            'mobile' => 'Phone',
                            'bell' => 'Bell',
                        ]
                    ],
                    'softDelete' => true,
                    'cacheSettings' => ['enableCache' => true]
                ]);
            ?>
        </div>
    </div>
</div>
```

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:2.2.4
- yii2-tree-manager version: dev-master 6984e77 

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-tree-manager without other plugins.

**Comment by kartik-v** [comment]
Can you debug your code and find out which input is being displayed on your browser console from which view?

**Comment by buttflattery** [comment]
@kartik-v it is coming from the `renderWidget()` method inside the `TreeView.php` at the very end of the method you are concatenating the input see below

```
public function renderWidget()
    {
        $content = strtr(
            $this->mainTemplate, [
                '{wrapper}' => $this->renderWrapper(),
                '{detail}' => $this->renderDetail(),
            ]
        );
        return strtr(
                $content, [
                    '{heading}' => $this->renderHeading(),
                    '{search}' => $this->renderSearch(),
                    '{toolbar}' => $this->renderToolbar(),
                ]
            ) . "\n" .
            Html::textInput('kv-node-selected', $this->value, $this->options) . "\n";
    }
```

**Comment by kartik-v** [comment]
Ok will create an enhancement. This is more to do with Krajee Base.
