### ISSUE TITLE
Undefined class constant 'BS_HIDE'

### ISSUE THREAD

**Issue by simialbi** [kartik-v/yii2-tree-manager#245]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. call `kartik\tree\TreeView::widget()` without setting `$hideCssClass`
2. Get error: Undefined class constant 'BS_HIDE'

![grafik](https://user-images.githubusercontent.com/3023342/55613397-e6c0a900-578a-11e9-838c-77857ebef9ac.png)

## Expected behavior and actual behavior

Not getting this error

## Environment

Not relevant

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

#### Libraries

- jQuery version: Not relevant
- yii2-tree-manager version: 1.1.2

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-tree-manager without other plugins.

**Comment by kartik-v** [comment]
This happens because you may have just manually copied/installed this extension without updating dependencies via composer. You do not seem to have the latest version of the dependency `yii2-krajee-base` which has this class. You need to run composer update and get all dependencies.
