### ISSUE TITLE
Invalid request signature detected during tree data manage action! Please refresh the page and retry.

### ISSUE THREAD

**Issue by jackp10** [kartik-v/yii2-tree-manager#246]
Hi @kartik-v
(sorry I have opened this new thread as the one I wrote to was marked as closed and I wasn't sure if you were able to see it.

I am having the exact same issue. I have copie the manage action into my own controller and altered it a little bit to accomodate my need.
Basically, I am trying to pass a DataProvider to nodeViewParams, which when I refresh the page, it works perfectly. I can see the GridView.
The problem start when I change node, which give me that "Operation Disallowed" message.
Without changing anything from the actual actionManage method, if I remove the dataProvider from the controller and also removing the GridView from the view, changing the node works again.

So that lead me to believe it is not something written in the actionManage method.

The thing is that I will have to add a new dataProvider inside the actionManage, as when the user click on a different node, I need to be able to show different data from different tables, but so far I can't even reach that point because I can't seems to be able to fix this initial issue.

I hope you can help,
( i have attached pieces of code to explain better my situation)
Alex

<img width="965" alt="Screenshot 2019-04-16 at 15 51 16" src="https://user-images.githubusercontent.com/9076655/56220125-d13b6100-605f-11e9-902e-452a7217cb73.png">
<img width="740" alt="Screenshot 2019-04-16 at 15 50 23" src="https://user-images.githubusercontent.com/9076655/56220126-d13b6100-605f-11e9-8160-f3b1e2f9db0c.png">

**Comment by kartik-v** [comment]
Need to understand your issue. Hope you are running the latest release of the extension and tested it after CLEANING up your browser cache and after CLEANING your web server runtime assets.
