### ISSUE TITLE
When 'show' => 'text' The icon box is show with one item 'text' 

### ISSUE THREAD

**Issue by BillHeaton** [kartik-v/yii2-tree-manager#259]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Reproducible on Demo
2. Select 'text' on 'Configure Icon As'
3. Click 'Apply Demo Config'
4. Notice that Icon checkboxlist still shows and has one item 'text'

## Expected behavior and actual behavior

When I follow those steps, I see...
Icon checkboxlist has one item 'text'

I was expecting...
Textbox with text items.  

#### Browsers

- [x ] Google Chrome
- [x ] Mozilla Firefox
- [ ] Internet Explorer
- [x ] Safari

#### Operating System

- [ ] Windows
- [x ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-tree-manager version: Latest

## Isolating the problem

- [x ] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [x ] The bug happens consistently across all tested browsers
- [x ] This bug happens when using yii2-tree-manager without other plugins.

**Comment by kartik-v** [comment]
Resolved. Cross check demo - you can set the icon show setting to one of `list`, `text` or `none`.

Just hard refresh your browser or clear cache before re-running the demo.
