### ISSUE TITLE
Override the detail view according to the selected nodes

### ISSUE THREAD

**Issue by fasi1208** [kartik-v/yii2-tree-manager#266]
First of all thanks for this awesome module. 

Is it possible that I can modify the detailed view on each node click? I want to add some extra information to it.

**Comment by kartik-v** [comment]
The extension already provides you the ability to do that via either `Module::treeViewSettings` or `TreeView::nodeAddlViews` where you can set part 1, 2, 3, 4 or 5 to customize or you can set your own view file via `TreeView::nodeView` or `Module::treeViewSettings['nodeView']`

**Comment by kartik-v** [comment]
Refer in the documentation about [nodeAddlViews](https://demos.krajee.com/tree-manager#treeview-nodeAddlViews)

**Comment by fasi1208** [comment]
Thank you for your quick response. As a newbie I am finding it hard to do it. Can you please share me any example which has implemented it ?
