### ISSUE TITLE
Show/Hide nodes to a user

### ISSUE THREAD

**Issue by fasi1208** [kartik-v/yii2-tree-manager#270]
I am able to add, remove, update nodes. There is one more requirement, that is to show/hide nodes on the basis of user access. i.e. when a user is given a specific node(s) then only that particular node(s) with all the child (if any) should be shown. 

**What I have done so far?**

I have created a table `user-node` in which I am assigning a node id to a user as shown below.

![image](https://user-images.githubusercontent.com/53753187/85978843-f748e900-b9f8-11ea-963b-d3471047d965.png)

**What I want to do**

Now I want to show only the specified node with its child node only and hide other nodes to that user

![image](https://user-images.githubusercontent.com/53753187/85978894-06c83200-b9f9-11ea-9604-f5bc3970fd12.png)

How can I achieve it?

**Comment by kartik-v** [comment]
Suggest you to read the documentation to understand the possibilities in this extension. Your use case can be achieved by reading about [Tree Model Methods](https://demos.krajee.com/tree-manager#model-methods). You can override the `isVisible` method within the tree model to show the node selectively for the current user or anything based on your custom condition.
