### ISSUE TITLE
Yii2- Hide admin settings based on user role

### ISSUE THREAD

**Issue by fasi1208** [kartik-v/yii2-tree-manager#273]
I have a tree in which I want to set `isAdmin`  parameter `true` or `false` based on `user_role`. I have done the following

`'isAdmin' => function(){
              if (Yii::$app->user->identity->user_role == 1)
              {
                  return true;
              }
              else
              {
                  return false;
              }
        },`

But I am getting an error 

> Operation Disallowed
Invalid request signature detected during tree data manage action! Please refresh the page and retry.
OLD HASH:
785a3cf9cbb1a90e862b718ed8ae3289944280448ae801de49d686aa5f70e951common\models\MdcNodehidebtn-default/mdc/backend/web/treemanager/node/save/mdc/backend/web/mdcnode/index@kvtree/views/_formw0-nodeselnodenodes<div class="kv-node-message">No valid nodes are available for display. Use toolbar buttons to add nodes.</div>111111{"id":"w0-nodeform"}{"1":"","2":"","3":"","4":"","5":""}{"submit":"<i class=\"glyphicon glyphicon-floppy-disk\"></i>","reset":"<i class=\"glyphicon glyphicon-repeat\"></i>"}a:0:{}[]list{"":"<em>Default</em> ( <span class=\"text-warning kv-node-icon kv-icon-parent\"><i class=\"fa fa-folder-close kv-node-closed\"></i></span> / <span class=\"text-warning kv-node-icon kv-icon-parent\"><i class=\"fa fa-folder-open kv-node-opened\"></i></span> / <span class=\"text-info kv-node-icon kv-icon-child\"><i class=\"fa fa-file\"></i></span>)","building":"<span class=\"fa fa-building\"></span> Building","folder":"<span class=\"fa fa-folder\"></span> Floor","user":"<span class=\"fa fa-user\"></span> Customer"}{"depth":"","glue":" &raquo; ","activeCss":"kv-crumb-active","untitled":"Untitled"}
NEW HASH:
e3037c327c2ddec080a38ce50002f825a214352f833f2acfe972c3d7d0a2b9abcommon\models\MdcNodehidebtn-default/mdc/backend/web/treemanager/node/save/mdc/backend/web/mdcnode/index@kvtree/views/_formw0-nodeselnodenodes<div class="kv-node-message">No valid nodes are available for display. Use toolbar buttons to add nodes.</div>11111{"id":"w0-nodeform"}{"1":"","2":"","3":"","4":"","5":""}{"submit":"<i class=\"glyphicon glyphicon-floppy-disk\"></i>","reset":"<i class=\"glyphicon glyphicon-repeat\"></i>"}a:0:{}[]list{"":"<em>Default</em> ( <span class=\"text-warning kv-node-icon kv-icon-parent\"><i class=\"fa fa-folder-close kv-node-closed\"></i></span> / <span class=\"text-warning kv-node-icon kv-icon-parent\"><i class=\"fa fa-folder-open kv-node-opened\"></i></span> / <span class=\"text-info kv-node-icon kv-icon-child\"><i class=\"fa fa-file\"></i></span>)","building":"<span class=\"fa fa-building\"></span> Building","folder":"<span class=\"fa fa-folder\"></span> Floor","user":"<span class=\"fa fa-user\"></span> Customer"}{"depth":"","glue":" &raquo; ","activeCss":"kv-crumb-active","untitled":"Untitled"}

I don't know what I am missing.

**Comment by gilangsugihardiansah** [comment]
try this 'isAdmin' => Yii::$app->user->identity->user_role == 1,

**Comment by kartik-v** [comment]
Yes - the `isAdmin` property should be a boolean value (and must not be a function as you have done).
