### ISSUE TITLE
Adding immediate parent ID rather than root ID

### ISSUE THREAD

**Issue by fasi1208** [kartik-v/yii2-tree-manager#274]
Hi. I am using this widget. It works around in a good way.  As you know that there will be `N` number of parents have `N` number of child. When a parent is created the `root` value is the value of its immediate parent. The same thing should be followed with child, for example, take a look of my structure

![image](https://user-images.githubusercontent.com/53753187/89493232-24916f80-d7cd-11ea-960f-e09d249e9479.png)

Below is my table structure 

![image](https://user-images.githubusercontent.com/53753187/89493318-54407780-d7cd-11ea-9c57-5523e0bdfc8e.png)

In above the root id of `Floor-1` is `1` which is perfectly ok as it's under the `Accurate`. But for `GIS Office` the root is also `1`. I think the root should be `2` as the parent of `GIS` is `Accurate` having ID `2` and vice versa. 

The reason that I have mentioned it is that it will help us to track/check/get all child nodes under the parent node. If there is any other way around to get all the child nodes of the parent nodes. For now, there is no tag/id for `parent-child` relationships in the table

**Comment by fasi1208** [comment]
No one to post an answer?

**Comment by kartik-v** [comment]
If you need a new root - you need to click/use the CREATE NEW ROOT button and not the CREATE CHILD button.
