### ISSUE TITLE
tree manager can't access nodeController with advanced template and pretty url

### ISSUE THREAD

**Issue by gilangsugihardiansah** [kartik-v/yii2-tree-manager#275]
hi all, how to run tree manager with advanced template and pretty url, becouse its not working in nodeActions, thx.
![Screenshot_2020-08-10 Admin-Simponi](https://user-images.githubusercontent.com/19811249/89750373-ead6a680-daf5-11ea-83d1-32d4d7da550e.png)

![Untitled](https://user-images.githubusercontent.com/19811249/90997491-e7f6ae00-e5eb-11ea-9583-f7719b0e8223.png)

**Comment by CrownStrong** [comment]
Try adding rules to urlManager. I'm not sure if this is correct


	'urlManager' => [
            /* ...Your parameters... */
            'rules' => [
                /* ...Your rules... */
                'treemanager/node/manage' => 'treemanager/node/manage',
                'treemanager/node/save' => 'treemanager/node/save',
                'treemanager/node/remove' => 'treemanager/node/remove',
                'treemanager/node/move' => 'treemanager/node/move',
                'treemanager/node' => 'treemanager/node',
             ],
     ],
