### ISSUE TITLE
Version 1.0.1

### ISSUE THREAD

**Issue by schmunk42** [kartik-v/yii2-tree-manager#31]
I saw some of your commits and this note: https://github.com/kartik-v/yii2-tree-manager/blob/master/CHANGE.md#version-101

So, are there more updates coming or is just the tag missing :smile:

**Comment by kartik-v** [comment]
These are tested updates for this release - not yet tagged yet.

There are a few other enhancements (mostly in my mind) - not sure I will have time to include all in this release... but will logically tag it soon.

**Comment by schmunk42** [comment]
IMHO you could just release (tag) a 1.0.1 and do the further updates later, since they are already tested.

**Comment by schmunk42** [comment]
Closing since we've a 1.0.1 :)
https://github.com/kartik-v/yii2-tree-manager/releases/tag/v1.0.1
