### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by blfox** [kartik-v/yii2-tree-manager#37]
Good day!
I need to add a relation so that the field 'name' id filed another table, and the derivation of the name of the id formed from this table.
For example:
tree table:
...
name - this id from 'another table'
...

another table
id
another_name
...
...
...

And when output is displayed another_name

How to register this functionality?

**Comment by kartik-v** [comment]
You need to have the `name` and `id` in same table - not sure why you want to break this basic DB design. The `id` attribute is the primary key and hence the `name` field pertaining to each Primary Key value must lie in the same table.

You can display and modify other relational data you need by just configuring `nodeAddlViews` to embed additional view content.
