### ISSUE TITLE
Enhancing tree container styles for smaller device screen sizes

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-tree-manager#44]
All working fine but thought I would request Tree.php as trait ideally or perhaps behaviour. Like a lot of people all of my models extend from my own extended ActiveRecord class (and my own ActiveQuery). I had errors that were awkward to get around so either had to extend Tree.php from my \common\components\ActiveRecord or turn Tree.php into a trait (Trait was a nice easy problem free option within minimal changes so I have it currently as a trait). Changes were minimal - but did have to comment out a few lines in TreeView.php where it tested for the model being derived from Tree.

The other change I needed was to modify find within Tree.php to attach nested set behaviour directly to my own ActiveQuery class - though this no major as the class derived from Tree can override find anyway - though have included here for possibility anyway.
```
    public static function find()
    {
        $query = get_called_class() . 'Query';
        $query = new $query(get_called_class());
        $query->attachBehavior(NULL, NestedSetsQueryBehavior::className());

        return $query;
    }
```

Perhaps I am missing something really obvious - long day. In order to use my own ActiveRecord, I couldn't see anyway other than altering Tree.php which isn't ideal for updates of course.

As another minor sub-issue, a suggestion on styling as below to add margin betwewn stacked containers on narrow width devices - if you close up your browser to iphone size you will see currently no margin between the containers in your demo
```
.kv-tree-wrapper, .kv-detail-container {
    margin-top: 20px;
}```

**Comment by kartik-v** [comment]
See multiple issues here. Breaking it down.

For the trait related enhancement check the enhancement #45.
