### ISSUE TITLE
Set a maximum nesting level

### ISSUE THREAD

**Issue by khain2007** [kartik-v/yii2-tree-manager#49]
Hi,

Firstly, thanks for your great work! It is an amazing extension for Yii2!

Are you thinking about implementing an option to set the maximum "lvl" for the tree? In this way it would be possible to limit the nesting level. I have this need in a specific project and I would need that option very badly... ;D

Thanks again for everything!

**Comment by MariusRumpf** [comment]
If needing this very badly you might consider writing a wrapper for the given controller where you check it by your own.

```php
class NodeController extends \kartik\tree\controllers\NodeController
{
    public function actionSave() {
        // Check the level here
        parent::actionSave();
    }

    public function actionMove() {
        // Check the level here
        parent::actionMove();
    }
} 
```
Set the `nodeActions` to use this controller then. 
Use the TreePluginEvents `treeview.selected` method to hide the add / move buttons from the ui according to the level.

**Comment by kartik-v** [comment]
Yes as an alternative to @MariusRumpf mentioned, you can also do this check for such data related validations within your `Tree` model as well and return a validation error (before validation or before saving). 

There can be many such validations needed -- that varies case to case and are individual application specific and its best left to the developer to handle this. This module currently has made it simple and offers you the ability to do that at this stage. Not sure if I want to overload all such use cases and validations.

**Comment by khain2007** [comment]
Thanks for the suggestions! I've made several changes, but I have an additional issue: I don't always receive the treeview.selected event (only the first time I check on a node). Here you have the code that I'm using:

$this->registerJs("
	var func = function(event, key) {
    	var lvl = parseInt($('#product-tree-tree ul').find('[data-key='+key+']').attr('data-lvl'));
    	var prd = $('#button-add-product');
    	if (lvl >= 2) {
	    	prd.attr('disabled', true);
	    }
	    else{
		    prd.attr('disabled', false);
		}
    };
	$('#product-tree').on('treeview.selected', func);
	$('#product-tree').on('treeview.beforeselect', func);
	$('#product-tree').on('treeview.create', function(event, parent) {
    	var lvl = parseInt($('#product-tree-tree ul').find('[data-key='+parent+']').attr('data-lvl'));
    	var prd = $('#button-add-product');
    	if (lvl >= 1) {
	    	prd.attr('disabled', true);
	    }
	    else{
		    prd.attr('disabled', false);
		}
	});
	");
