### ISSUE TITLE
cant add a root node

### ISSUE THREAD

**Issue by cornernote** [kartik-v/yii2-tree-manager#50]
I am trying to get started with `TreeView::widget()`.  I followed the guide, and I see the interface.  When I click add a new root I get the following:

ajax request to: http://192.168.2.130:82/index.php?r=treemanager%2Fnode%2Fmanage&kvtree=-959722365

```json
{"name":"Exception","message":"Invalid JSON data.","code":0,"type":"yii\\base\\InvalidParamException"
,"file":"/app/vendor/yiisoft/yii2/helpers/BaseJson.php","line":68,"stack-trace"
:["#0 /app/vendor/kartik-v/yii2-tree-manager/controllers/NodeController.php
(103): yii\\helpers\\BaseJson::decode(Array)","#1 [internal function]: kartik\\tree\\controllers\\NodeController-
>actionManage()","#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(55):
 call_user_func_array(Array, Array)","#3 /app/vendor/yiisoft/yii2/base/Controller
.php(151): yii\\base\\InlineAction->runWithParams(Array)","#4 /app/vendor
/yiisoft/yii2/base/Module.php(455): yii\\base\\Controller->runAction('manage', Array)","#5 /app
/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('treemanager/nod...', Array
)","#6 /app/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application-
>handleRequest(Object(yii\\web\\Request))","#7 /app/web/index.php(14): yii
\\base\\Application->run()","#8 {main}"]}
```

Do you know what I am doing wrong?

**Comment by luckynvic** [comment]
I can add new root only if admin mode = true and soft delete = true. Disable admin mode or soft delete make widget fail to add new node. If you look into log, new record just deleted after inserted. 
This my view  : 
```php
echo TreeView::widget([
	'query' => Instansi::find()->addOrderBy('root, lft'),
	'isAdmin' => false,
	'softDelete' => false,
]);
```
This my log  :
![image 1](https://cloud.githubusercontent.com/assets/4830453/9021210/3bcdf85c-3869-11e5-91da-69e17de16522.png)

I've tried in [demo page](http://demos.krajee.com/tree-manager-demo/tree-view) then configure admin mode = false, soft delete = false, it's fail to add new root too. For the solution now, i configure admin mode = true and soft delete = true.
