### ISSUE TITLE
$treeQueryClass declaration in trait

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-tree-manager#51]
Don't think $treeQueryClass property should be declared in TreeTrait - just in the model that uses it.

This would only be noticed when someone uses this property

**Comment by kartik-v** [comment]
This is also true for a few other properties... will push an update.

**Comment by kartik-v** [comment]
This is also true for a few other properties... will push an update. However you must include these properties in your model else an exception will be thrown.

**Comment by andrewblake1** [comment]
unless use isset or similar around them in the trait then could use a private or const instead of if not set perhaps  … would save having to declare them in the model unless needed.
