### ISSUE TITLE
NodeController trait

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-tree-manager#53]
Hi Kartik

Could also make NodeController a trait for similar reasons as previously for the model.

FYI I have described my use case below - I am not suggesting to change kv-tree.js as I think that is just something I am going to have to maintain in my own code however I thought it may be useful for you at some stage in the future to understand different ways that people are using your code in case it helps to make it more easily extended :

Extending my own controller and using NodeController as a trait, with a couple of very minor alterations to kv-tree.js, when I select a node rather than ajax update of the form I am redirecting to the update action of my normal controller which allows for url to change to reflect the selected id and to update my breadcrumbs in a consistent manner with the rest of my application - and a few other things as suitable in this circumstance. I wouldn't suggest that everyone would want to do this - the existing way is natural for a different model in my system. I have embedded the treeview widget into that update view so in essence it looks the same but with correct navigation items like breadcrumbs and a more useful url for linking to if necessary. I updated kv-tree.js to include an update method which is called instead of manage when selected and that is a simple 1 line redirect to the url based on a new nodeAction key of 'update' - as follows:

```
update: function (key) {
    location.href = this.actions.update + key;
},
select: function (key, init, mesg) {
...
            } else {
                self.update(key);
            }
```
and in my view
```
        'nodeActions' => [
            'update' => Yii::$app->urlManager->baseUrl . '/' . $this->context->id . '/',
            Module::NODE_MANAGE => Url::to(['manage'] ...
```

I havn't tested everything yet but the above changes so far seem to have achieved what I needed. NB I don't need a view action as I use your DetailView and just detect from the users access rights for a particular model whether they should edit or view.

**Comment by kartik-v** [comment]
While I understand a trait is possible, but not sure why its needed.

You can have your own Controller that renders the TreeView... but another controller that manages the treeview actions.

**Comment by andrewblake1** [comment]
I think you are correct. In hind site I think I took a more difficult route than I needed. I probably should just use the beforeselect event to redirect to an action of my choosing in my own controller as you state. Thankyou.
