### ISSUE TITLE
id attribute not found

### ISSUE THREAD

**Issue by kapelan** [kartik-v/yii2-tree-manager#54]
Every try to update a tree node was causing an error("id attribute not found"). 
 Solution:
in views/_form.php line 56: 
$options = ['disable' => true];

change to:

$options = ['readonly' => true];

Disabled inputs are not passed by post.

**Comment by kartik-v** [comment]
Is there any need why you want the `id` attribute to be passed as post?

- The `id` attribute is typically autogenerated as a primary key for a NEW record.
- For an an update action - the `id` is passed as a parameter to query the record and is already available with the model.
