### ISSUE TITLE
Yii2: navbar dropdown is disabled when TreeView widget is active

### ISSUE THREAD

**Issue by ppokrovsky** [kartik-v/yii2-tree-manager#55]
Hi,

I have a small problem with TreeView::widget.

When it is initialized as
```
TreeView::widget([
    'query' => Category::find()->addOrderBy('root, lft'),
    'headingOptions' => ['label' => Yii::t('app', 'Categories')],
    'softDelete' => false,
    'fontAwesome' => false,
    'displayValue' => 1,
    'isAdmin' => false,
]);
```

it disables bootstrap navbar dropdown menu. It happens when `'displayValue'` is set to `1` or when any node is selected.

Navbar is added as a widget:
```
Nav::widget([
     'options' => ['class' => 'navbar-nav'],
     'items' => [
         ['label' => Yii::t('app', 'Catalog'), 'items' => [
             ['label' => Yii::t('app', 'Products'), 'url' => ['/product']],
             ['label' => Yii::t('app', 'Categories'), 'url' => ['/category']],
             ['label' => Yii::t('app', 'Manufacturers'), 'url' => ['/manufacturer']],
         ],
    ],
]);
```

So if I click `Catalog` with TreeView widget active, nothing happens, no dropdown is displayed.

I guess there might be a CSS override somewhere in TreeView widget, which prevents dropdown to work properly, but could not find any reference.  No obvious errors in browser console either.

Is there a workaround for this?

Thank you.

**Comment by kapelan** [comment]
Does It happens only when 'displayValue' is set to 1 or when any node is selected?

For me It looks like the  bootstrap.js is loading more than once. To prevent situation like this, in your AppAssets change in 'depends' array a row :

'yii\bootstrap\BootstrapAsset'
replace on:

'yii\bootstrap\BootstrapPluginAsset',

I hope it will help

**Comment by ppokrovsky** [comment]
@kapelan it happens when any node is selected, which is with `'displayValue' => true` is a default state. You're right, `bootstrap.js` is indeed loaded twice. My config is not default: my theme overrides `AppAsset` heavily, so I will have to play around with it. 
Thank you for you help!

**Comment by kartik-v** [comment]
It seems as an issue in your application of other JS scripts or plugins loading twice causing this. Check with a brand new yii app without any plugins and just this extension installed and work from there to find what is your app specific issue.
