### ISSUE TITLE
Possible small bug beforeselect

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-tree-manager#56]
Not 100% sure if it is something I have configured wrong, or if it is desired or if bug but:

treeview.beforeselect appears to be firing on click of "add new" button option - apologies I havn't tested or stepped thru further but thought I would raise this issue for you to double check if it is the case and if it is desired.

I expected it to just fire on tree node selection - as per the documentation. No major as can just test for key === null however thought I should raise issue for you to check.

**Comment by kartik-v** [comment]
Yes on clicking add new the new node is selected by default... so the event firing is expected.

**Comment by andrewblake1** [comment]
That makes sense.  Thanks for the explanation.
