### ISSUE TITLE
Class 'Tree' not found

### ISSUE THREAD

**Issue by des1roer** [kartik-v/yii2-tree-manager#60]
using get this error

    use yii\helpers\Html;
    use kartik\tree\TreeView;
    echo TreeView::widget([
        // single query fetch to render the tree
        'query'             => Tree::find()->addOrderBy('root, lft'), 
        'headingOptions'    => ['label' => 'Categories'],
        'isAdmin'           => false,                       // optional (toggle to enable admin mode)
        'displayValue'      => 1,                           // initial display value
        //'softDelete'      => true,                        // normally not needed to change
        //'cacheSettings'   => ['enableCache' => true]      // normally not needed to change
    ]);

**Comment by kartik-v** [comment]
You need to FULLY namespace all your classes in Yii2 - else you will get a class not found error. This may have been missed in docs -- but you need to point your `Tree` class to the fully namespaced Tree model which you need to create as described in documentation.
