### ISSUE TITLE
defaults

### ISSUE THREAD

**Issue by des1roer** [kartik-v/yii2-tree-manager#61]
when you try to add a new item get

    Nested set left property cannot be blank.
    Nested set right property cannot be blank.
    Nested set level / depth cannot be blank.

**Comment by marwamourad** [comment]
Hey,
i faced this problem and solved it.
you can just remove the rule form the model class
/*[['lft', 'rgt', 'lvl', 'name'], 'required'],*/

**Comment by kartik-v** [comment]
No... these attributes are mandatory for a nested set tree node.

**Comment by satoved** [comment]
I have the same froblem. Does anyone know the solution?
Thanks.

**Comment by kartik-v** [comment]
If you are using a `TreeTrait` ensure that your Tree model has the other attributes defined exactly as per `kartik\tree\models\Tree` class. This is needed if you are using the default tree actions and not your own controller actions for the tree manipulation.

**Comment by kartik-v** [comment]
This is mentioned with the example in the [Setup Model in Getting Started Section](http://demos.krajee.com/tree-manager#setup-model) of the documentation.

**Comment by satoved** [comment]
Thanks for reply.

I use extending, not traits
`class Tree extends \kartik\tree\models\Tree`

I think the problem is in the rules() of my Tree class.
It's generated by gii and 'lft', 'rgt', 'lvl' are required.

It seems like the validation method is called before the behavior sets this attributes. So the error is throwed.

**Comment by kartik-v** [comment]
Yes you need to match this with the tree model provided with the extension.. Internal attributes like these should not have any validation rules.
