### ISSUE TITLE
Several category tables

### ISSUE THREAD

**Issue by satoved** [kartik-v/yii2-tree-manager#76]
Can I use the extenstion if I have several category tables?

For example:
- "tbl_book_category" with PK "book_category_id"
- "tbl_author_category" with PK "author_category_id"

I want to use them separately, but in my config file there is only one 'keyAttribute' => 'id' string.

Thanks for help.

**Comment by kartik-v** [comment]
Yes you can create different models extending from `kartik\tree\models\Tree`, e.g.

- `class Book extends \kartik\tree\models\Tree`
- `class AuthorCat extends \kartik\tree\models\Tree`
