### ISSUE TITLE
TreeViewInput does not work with asDropdown = true

### ISSUE THREAD

**Issue by rimas-kudelis** [kartik-v/yii2-tree-manager#77]
I have the following piece of code in my form:
```php
    <?= $form->field($model, 'category_id')->widget(TreeViewInput::classname(), [
        'name' => 'category_list',
        'value' => true,
        'query' => \app\models\VacancyCategory::find()->addOrderBy('root, lft'),
        'fontAwesome' => true,
        'multiple' => false,
        'rootOptions' => ['label'=>''],
        'asDropdown' => true,
        'wrapperTemplate' => '{tree}{footer}',
        'options' => ['disabled' => false],
    ]) ?>
```
And it doesn't work. Well, the field is displayed, but clicking on it does nothing. Changing `asDropdown` to `false` makes it work!

What also makes it work is including a `TreeView` widget in that form as well. I suppose it might be something JS related?

**Comment by kartik-v** [comment]
Seems duplicate to #78. Refer [related comment](https://github.com/kartik-v/yii2-tree-manager/issues/78#issuecomment-153232759).

**Comment by evgenybukharev** [comment]
TreeViewInput does not work with asDropdown = true and when loaded bootstrap.js, if you disable load bootstrap.js all works well

**Comment by kartik-v** [comment]
It probably is something to do with other plugin conflict or bootstrap.js loading twice on your page. You need to check the same or control the assets via yii asset manager component.
