### ISSUE TITLE
Please make it possible to hide the pseudo-root in TreeViewInput

### ISSUE THREAD

**Issue by rimas-kudelis** [kartik-v/yii2-tree-manager#79]
I have a tree with multiple roots, but `TreeViewInput` adds an additional root on top of them all. Is there a way to not output it?

I could hide it with CSS, but that's not what I want, because all the branches would still be displayed as branching from it. What I want is a configuration option to just not output it at all, and the `TreeViewInput` to design its output accordingly in such situation.

Here's a screenshot. I hope you would agree that it looks a bit ugly with that pseudo-root node in place.
![treeview screenshot](https://cloud.githubusercontent.com/assets/2812673/10902844/98696146-820b-11e5-9236-8ff59a1fdd5c.png)

**Comment by kartik-v** [comment]
It is needed for two reasons:

- collapse all nodes and expand all nodes
- CSS styling of tree indicators to work appropriately (the way the nested set is fetched).

**Comment by rimas-kudelis** [comment]
I do understand that it expands/collapses all nodes, but I don't think everyone needs that functionality, at least I don't, so I'd gladly trade that ability for the possibility to hide this pseudo-root element.

Regarding CSS, are you sure this can't be reimplemented differently?

**Comment by kartik-v** [comment]
> Regarding CSS, are you sure this can't be reimplemented differently?

Not sure I can commit this as need to check this when I get time. If you do find an option to enhance this let know.

**Comment by kartik-v** [comment]
> Regarding CSS, are you sure this can't be reimplemented differently?

Not sure I can commit this as need to check this when I get time. I do foresee some difficulty and changes. 

If you do find an option to enhance this let know.

**Comment by kartik-v** [comment]
Currently closing as wontfix... can reopen it if someone wishes to suggest any enhancement for this.

**Comment by bubifengyun** [comment]
I think that the root can be set as a comment. for example, if I can control many units, where some units have their children, I can write as follows.

```php
// in TreeView
'query'=>Tree::findOne($control_ID)
->children()
->orWhere(['id'=>$control_ID]),
'rootOptions'=>['label'=>'Unit I Can Control'],
```

can this call `make useless to be useful`

thank you.

**Comment by kartik-v** [comment]
This is resolved and made more configurable via enhancements in #178.
