### ISSUE TITLE
Boolean values (removable etc) do not work with the model using TreeTrait

### ISSUE THREAD

**Issue by jussiaho** [kartik-v/yii2-tree-manager#80]
At least if you don't save the flags in the database, you need to set the attributes the following way:

```php
public $removable = 1;
```
or
```php
    public function getRemovable()
    {
        return 1;
    }
```

This won't work:

```php
public $removable = true;
```
nor
```php
    public function getRemovable()
    {
        return true;
    }
```

**Comment by kartik-v** [comment]
Not clear with your query. Depending on your need you can set the `removable` property as mentioned above in your model ... or you can directly override the `isRemovable` method.

**Comment by jussiaho** [comment]
The problem is that if I use virtual attributes or `isRemovable` method, I cannot use real boolean (true/false) values in PHP but I have to use integer values 1/0. If a value is meant to be a boolean value, true and false should be usable.

**Comment by kartik-v** [comment]
This is fixed. You may check now.
