### ISSUE TITLE
No easy way to add rules when using TreeTrait

### ISSUE THREAD

**Issue by maz0717** [kartik-v/yii2-tree-manager#81]
If you are using TreeTrait vs extending Tree, you cannot add rules because the rules function will override the rules in TreeTrait.

**Comment by kartik-v** [comment]
Not sure of what is your query? Probably you are not clear on using PHP traits. It depends on you how you wish to code and program your app, whether overriding the `Tree` class or using the `TreeTrait` in your class.

If your question is how you override a trait method - you may want to read PHP programming documentation for using traits.

To use a parent method for the `TreeTrait`, this is explained to an extent in the [documentation in the model setup section]().

```php
class Product extends \yii\db\ActiveRecord
{
    use \kartik\tree\models\TreeTrait {
        rules as parentRules; // note the alias
    }
    
    public function rules() {
        $rules = $this->parentRules();
    }
}
```
