### ISSUE TITLE
Change anonymous behavior to a named one.

### ISSUE THREAD

**Issue by maz0717** [kartik-v/yii2-tree-manager#82]
There is no way to temporarily disable the tree behavior because it is created as an anonymous behavior.  You can only disable all traits.  I suggest naming the behavior as "tree" like the nested set documentation.

**Comment by kartik-v** [comment]
You can always override the `behaviors` method to get what you want...

**Comment by maz0717** [comment]
If I override the behaviors, then I have to check with each update that nothing was added to behaviors.  Creocoder's documentation examples names the behavior as tree.  All I am really asking for is to change the TreeTrait behaviours function from:

 public function behaviors()
    {
        $module = TreeView::module();
        $settings = ['class' => NestedSetsBehavior::className()] + $module->treeStructure;
        return [$settings];
    }

to:
 public function behaviors()
    {
        $module = TreeView::module();
        // Not really sure where to end the array, but this is the line that needs changed.
        $settings = ['tree'=>['class' => NestedSetsBehavior::className()] ] + $module->treeStructure;
        return [$settings];
    }

Similar to the way it is documented in creocoders nested set documentation for configuring the model.

As it is currently an anonymous behavior, this shouldn't affect backwards compatibility as the only way to disable the behavior currently is to disable all the behaviors.  For reference, I came across this problem by following the advice of issue #58 of creocoder's yii2-nested-sets.

https://github.com/creocoder/yii2-nested-sets/issues/58

For anyone else coming across this issue, you have to call $node->detachBehaviors() to temporarily disable all behaviors.

**Comment by kartik-v** [comment]
Sure will consider an enhancement for this... you can submit enhancements via a pull request as well..

**Comment by kartik-v** [comment]
Fixed via the commit. A new module property called `treeBehaviorName` as been added (defaults to `tree`).
