### ISSUE TITLE
TreeView widget as a tree controlled (filtered) gridview

### ISSUE THREAD

**Issue by firstau** [kartik-v/yii2-tree-manager#91]
Hi Kartik, 
Is it possible to make the widget as a tree controlled gridview like following?
1. click any item/node of left side tree, the right side gridview will list all rows of an related table relating to selected item/node and its child item/node;
2. users will be able to view the tree and select the tree item/node only, but they can edit the gridview area. The Admin can create, update, delete node.

If it is possible, which areas of your yii2-tree-manager we need to do the changes and what we need to take care to make this Treeview widget working properly after the changes?

Thanks in advance.

**Comment by kartik-v** [comment]
You may read the [TreeView documentation](http://demos.krajee.com/treeview) and read the Module and TreeView widget sections. 

Just change the `TreeView::nodeView` or `Module::nodeView` to point to your view file that renders the gridview -  (you may read the view file comments... what you need to retain in the view file)...

That is the most advanced customization you can do... but if you want it simpler... you may setup `nodeAddlViews` that embeds additional content in your view file. Read the docs.

**Comment by firstau** [comment]
Thanks Kartik. I will try it in next a few days..

**Comment by firstau** [comment]
Hi Kartik, I tried to use nodeAddlViews to show an added column "preEmployeeId" of tbl_Jobtree table (I rename the tbl_Tree to tbl_Jobtree) and I did the following changes as per instruction:
1. configured tableName to tbl_Jobtree;
2. added 'preEmployeeId' to @property and  attributeLabels() function of the TblJobtree model;
3.  added     
     'nodeAddlViews'=>[
      kartik\tree\Module::VIEW_PART_2 =>'@frontend/views/tbljobtree/_treePart2'  
    ],
into TreeView::widget in index.php file of the tbljobtree views folder
4. created new _treePart2.php with the code:
<?php
//@frontend/views/tbljobtree/_treePart2
echo $form->field($node, 'PreEmployeeId')->textArea();
?>

But I get the error for the VIEW_PART_2:
"Getting unknown property: frontend\models\TblJobtree::PreEmployeeId" pointed to the line in the _treePart2.php

Everything was ok before I added the VIEW_PART_2. Could you please let me know how can I correct this?

**Comment by firstau** [comment]
I figured out the error. it was typeo.  PreEmployeeId should be preEmployeeId. all good.

**Comment by bubifengyun** [comment]
all work well? I find the same error to my code. Could you share your code? thank you.

**Comment by bubifengyun** [comment]
OK, mine works well now. I read the document carefully and find that it should be 

```php
'nodeView'=>'@frontend/views/site/nodeview'
```

I write less code.

**Comment by bubifengyun** [comment]
Hi, @firstau , there's so many problems when i code this issue in my project. Can you share your way how to complete this work.

Now, I meet this problem.

when i click tree in the left, the right gridview will be changed. but when the girdview has a filter, it can not filter at all. it render just as

```php
{"name":"Exception","message":"This operation is not allowed.","code":0,"type":"yii\\base\\InvalidCallException","file":"/opt/lampp/htdocs/www/wuzhishan/vendor/kartik-v/yii2-tree-manager/controllers/NodeController.php","line":73,"stack-trace":["#0 /opt/lampp/htdocs/www/wuzhishan/vendor/kartik-v/yii2-tree-manager/controllers/NodeController.php(159): kartik\\tree\\controllers\\NodeController::checkValidRequest()","#1 [internal function]: kartik\\tree\\controllers\\NodeController->actionManage()","#2 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)","#3 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/base/Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)","#4 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/base/Module.php(455): yii\\base\\Controller->runAction('manage', Array)","#5 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('treemanager/nod...', Array)","#6 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#7 /opt/lampp/htdocs/www/wuzhishan/frontend/web/index.php(18): yii\\base\\Application->run()","#8 {main}"]}
```

I find the url will be directed to `..?r=site/out/treemanager%2Fnode%2Fmanage&kvtree=-978960995`, 
but the url should be `..?r=site/out`. 

Thank you.
