### ISSUE TITLE
TreeTrait not found

### ISSUE THREAD

**Issue by mmx3** [kartik-v/yii2-tree-manager#93]
Noticed that TreeTrait was updated 8 days ago, but could not find it in the module's model directory.

**Comment by kartik-v** [comment]
You may want to check your environment. The TreeTrait is al[l fine in models directory here](https://github.com/kartik-v/yii2-tree-manager/tree/master/models).

**Comment by mmx3** [comment]
Manually installed the latest files. Environment is fine. For some reason, composer isn't updating to my Windows box. Not sure why. Appreciate the quick response.
