### ISSUE TITLE
Check node moveable

### ISSUE THREAD

**Issue by StApostol** [kartik-v/yii2-tree-manager#94]
Hi, maybe in a https://github.com/kartik-v/yii2-tree-manager/blob/master/controllers/NodeController.php#L258 need to add code and etc.
```
if ($nodeFrom->movable_u == 0) {
    return false;
}
```

**Comment by kartik-v** [comment]
Resolved via [upgrade to release v1.0.5](https://github.com/kartik-v/yii2-tree-manager/commit/0fd506de3ef0c73ec8a3f0c9267ed8353f5e9f89).
