### ISSUE TITLE
function isDisabled() source of the problem

### ISSUE THREAD

**Issue by pceuropa** [kartik-v/yii2-tree-manager#95]
In my default configuration: Yii2 2.0.6 basic
When  function (app\models\Product) isDisabled() have 
```
Yii::$app->user->username
```
Form editing not work, return error: Getting unknown property: yii\web\User::username

**Comment by kartik-v** [comment]
The message is clear. You need to check why you have overridden isDisabled with yii app user condition and check your user component configuration is valid for your app.
