### ISSUE TITLE
Get array tree for SideNav, is it possible?

### ISSUE THREAD

**Issue by igorbelikov** [kartik-v/yii2-tree-manager#97]
Hi, Kartik! Thanks for this extension!

I use it to create categories and faced such problem. How can I pass this tree to build the plugin menu SideNav?
Just it turns out that I can create a backend that tree, and bring to the front end - I can not.

**Comment by igorbelikov** [comment]
Kartik, if it is not implemented, then I solved the problem myself, and if you want, you can do a pool request, which will expand your functionality and will be able to produce wood in the form of an array (which can be used for Nav components).
![image](https://cloud.githubusercontent.com/assets/6455277/12378807/b2e89f50-bd52-11e5-8956-e1591ac93043.png)
![image](https://cloud.githubusercontent.com/assets/6455277/12378821/0c09e81e-bd53-11e5-845f-c24e641d8ff5.png)

**Comment by kartik-v** [comment]
Sure you can submit a **pull request**.

**Comment by igorbelikov** [comment]
Ok, I'm sorry, I corrected a comment. :-)

**Comment by HanafiAhmat** [comment]
Hi @igorbelikov, any updates on this?

**Comment by igorbelikov** [comment]
@HanafiAhmat, I began to prepare the update, but then I was busy and distracted in the coming days will send a pull request.
