### ISSUE TITLE
Make Tree View Input auto close on select optional.

### ISSUE THREAD

**Issue by maz0717** [kartik-v/yii2-tree-manager#98]
Currently, the tree view input dropdown closes when selecting an item.  This doesn't make much sense when the "multiple" option is enabled.  Please either make the dropdown close on selection a configurable option, or don't automatically close the dropdown if the multiple option is true.

**Comment by kartik-v** [comment]
Resolved via latest update to rel v1.0.6. New boolean property `TreeViewInput::autoCloseOnSelect` available that defaults to `true` (can set it to `false` to not auto close).

**Comment by Fluit** [comment]
therefore this is added in kv-tree-input.js:
` self.$element.on('treeview:change', function (event, keys, desc) {
                self.setInput(desc.split(','));
                if (self.autoCloseOnSelect) {
                    self.$input.closest('.kv-tree-dropdown-container').removeClass('open');
                }
            });`
But in the rendered HTML there is: `<div class="dropdown kv-tree-dropdown-container show">`

It still doesnt work.
